package voronoiaoc.byg.common.world.feature.features.overworld.trees.coniferous;

import com.mojang.datafixers.Dynamic;
import net.minecraft.util.math.BlockPos;
import net.minecraft.util.math.MutableBoundingBox;
import net.minecraft.world.gen.IWorldGenerationBaseReader;
import net.minecraft.world.gen.IWorldGenerationReader;
import net.minecraft.world.gen.feature.NoFeatureConfig;
import voronoiaoc.byg.common.world.feature.features.overworld.trees.util.BYGAbstractTreeFeature;
import voronoiaoc.byg.core.byglists.BYGBlockList;

import java.util.Random;
import java.util.Set;
import java.util.function.Function;

public class ConiferTree3 extends BYGAbstractTreeFeature<NoFeatureConfig> {

    public ConiferTree3(Function<Dynamic<?>, ? extends NoFeatureConfig> configIn) {
        super(configIn);
    }

    protected boolean place(Set<BlockPos> changedBlocks, IWorldGenerationReader worldIn, Random rand, BlockPos pos, MutableBoundingBox boundsIn) {
        int randTreeHeight = 23 + rand.nextInt(5);
        BlockPos.Mutable mainmutable = new BlockPos.Mutable(pos);

        if (pos.getY() >= 1 && pos.getY() + randTreeHeight + 1 < 256) {
            BlockPos blockpos = pos.down();
            if (!isSoil(worldIn, blockpos, getSapling())) {
                return false;
            } else if (!this.doesTreeFit(worldIn, pos, randTreeHeight)) {
                return false;
            } else {
                this.treeLog(changedBlocks, worldIn, mainmutable.add(0, 0, 0), boundsIn);
                this.treeLog(changedBlocks, worldIn, mainmutable.add(0, 1, 0), boundsIn);
                this.treeLog(changedBlocks, worldIn, mainmutable.add(0, 2, 0), boundsIn);
                this.treeLog(changedBlocks, worldIn, mainmutable.add(0, 3, 0), boundsIn);
                this.treeLog(changedBlocks, worldIn, mainmutable.add(0, 4, 0), boundsIn);
                this.treeLog(changedBlocks, worldIn, mainmutable.add(0, 5, 0), boundsIn);
                this.treeLog(changedBlocks, worldIn, mainmutable.add(0, 6, 0), boundsIn);
                this.treeLog(changedBlocks, worldIn, mainmutable.add(0, 7, 0), boundsIn);
                this.treeLog(changedBlocks, worldIn, mainmutable.add(0, 8, 0), boundsIn);
                this.treeLog(changedBlocks, worldIn, mainmutable.add(0, 9, 0), boundsIn);
                this.treeLog(changedBlocks, worldIn, mainmutable.add(0, 10, 0), boundsIn);
                this.treeLog(changedBlocks, worldIn, mainmutable.add(0, 11, 0), boundsIn);
                this.treeLog(changedBlocks, worldIn, mainmutable.add(0, 12, 0), boundsIn);
                this.treeLog(changedBlocks, worldIn, mainmutable.add(0, 13, 0), boundsIn);
                this.treeLog(changedBlocks, worldIn, mainmutable.add(0, 14, 0), boundsIn);
                this.treeLog(changedBlocks, worldIn, mainmutable.add(0, 15, 0), boundsIn);
                this.treeLog(changedBlocks, worldIn, mainmutable.add(0, 16, 0), boundsIn);
                this.treeLog(changedBlocks, worldIn, mainmutable.add(0, 17, 0), boundsIn);
                this.treeLog(changedBlocks, worldIn, mainmutable.add(0, 18, 0), boundsIn);
                this.treeLog(changedBlocks, worldIn, mainmutable.add(0, 19, 0), boundsIn);
                this.treeLog(changedBlocks, worldIn, mainmutable.add(0, 20, 0), boundsIn);
                this.treeLog(changedBlocks, worldIn, mainmutable.add(0, 21, 0), boundsIn);
                this.treeLog(changedBlocks, worldIn, mainmutable.add(0, 22, 0), boundsIn);
                this.treeLog(changedBlocks, worldIn, mainmutable.add(0, 23, 0), boundsIn);
                this.treeLog(changedBlocks, worldIn, mainmutable.add(0, 24, 0), boundsIn);
                this.treeLog(changedBlocks, worldIn, mainmutable.add(0, 25, 0), boundsIn);
                this.treeLog(changedBlocks, worldIn, mainmutable.add(0, 26, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 11, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 11, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 11, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 11, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-2, 12, -3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 12, -3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 12, -3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 12, -3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(2, 12, -3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-3, 12, -2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-2, 12, -2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 12, -2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 12, -2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 12, -2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(2, 12, -2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(3, 12, -2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-3, 12, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-2, 12, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 12, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 12, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 12, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(2, 12, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(3, 12, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-3, 12, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-2, 12, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 12, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 12, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(2, 12, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(3, 12, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-3, 12, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-2, 12, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 12, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 12, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 12, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(2, 12, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(3, 12, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-3, 12, 2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-2, 12, 2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 12, 2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 12, 2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 12, 2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(2, 12, 2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(3, 12, 2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-2, 12, 3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 12, 3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 12, 3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 12, 3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(2, 12, 3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 13, -2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 13, -2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 13, -2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-2, 13, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 13, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 13, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 13, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(2, 13, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-2, 13, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 13, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 13, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(2, 13, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-2, 13, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 13, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 13, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 13, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(2, 13, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 13, 2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 13, 2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 13, 2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-2, 14, -3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 14, -3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 14, -3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 14, -3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(2, 14, -3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-3, 14, -2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-2, 14, -2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 14, -2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 14, -2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 14, -2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(2, 14, -2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(3, 14, -2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-3, 14, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-2, 14, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 14, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 14, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 14, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(2, 14, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(3, 14, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-3, 14, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-2, 14, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 14, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 14, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(2, 14, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(3, 14, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-3, 14, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-2, 14, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 14, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 14, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 14, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(2, 14, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(3, 14, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-3, 14, 2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-2, 14, 2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 14, 2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 14, 2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 14, 2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(2, 14, 2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(3, 14, 2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-2, 14, 3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 14, 3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 14, 3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 14, 3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(2, 14, 3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 15, -2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 15, -2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 15, -2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-2, 15, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 15, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 15, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 15, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(2, 15, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-2, 15, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 15, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 15, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(2, 15, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-2, 15, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 15, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 15, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 15, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(2, 15, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 15, 2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 15, 2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 15, 2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 16, -4), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 16, -4), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 16, -4), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-2, 16, -3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 16, -3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 16, -3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 16, -3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(2, 16, -3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-3, 16, -2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-2, 16, -2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 16, -2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 16, -2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 16, -2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(2, 16, -2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(3, 16, -2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-4, 16, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-3, 16, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-2, 16, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 16, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 16, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 16, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(2, 16, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(3, 16, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(4, 16, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-4, 16, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-3, 16, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-2, 16, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 16, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 16, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(2, 16, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(3, 16, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(4, 16, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-4, 16, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-3, 16, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-2, 16, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 16, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 16, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 16, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(2, 16, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(3, 16, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(4, 16, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-3, 16, 2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-2, 16, 2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 16, 2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 16, 2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 16, 2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(2, 16, 2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(3, 16, 2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-2, 16, 3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 16, 3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 16, 3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 16, 3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(2, 16, 3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 16, 4), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 16, 4), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 16, 4), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 17, -2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 17, -2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 17, -2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-2, 17, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 17, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 17, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 17, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(2, 17, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-2, 17, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 17, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 17, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(2, 17, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-2, 17, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 17, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 17, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 17, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(2, 17, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 17, 2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 17, 2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 17, 2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 18, -4), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 18, -4), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 18, -4), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-2, 18, -3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 18, -3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 18, -3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 18, -3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(2, 18, -3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-3, 18, -2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-2, 18, -2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 18, -2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 18, -2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 18, -2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(2, 18, -2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(3, 18, -2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-4, 18, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-3, 18, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-2, 18, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 18, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 18, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 18, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(2, 18, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(3, 18, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(4, 18, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-4, 18, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-3, 18, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-2, 18, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 18, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 18, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(2, 18, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(3, 18, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(4, 18, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-4, 18, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-3, 18, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-2, 18, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 18, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 18, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 18, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(2, 18, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(3, 18, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(4, 18, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-3, 18, 2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-2, 18, 2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 18, 2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 18, 2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 18, 2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(2, 18, 2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(3, 18, 2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-2, 18, 3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 18, 3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 18, 3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 18, 3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(2, 18, 3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 18, 4), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 18, 4), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 18, 4), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 19, -2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 19, -2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 19, -2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-2, 19, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 19, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 19, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 19, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(2, 19, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-2, 19, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 19, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 19, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(2, 19, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-2, 19, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 19, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 19, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 19, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(2, 19, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 19, 2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 19, 2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 19, 2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-2, 20, -3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 20, -3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 20, -3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 20, -3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(2, 20, -3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-3, 20, -2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-2, 20, -2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 20, -2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 20, -2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 20, -2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(2, 20, -2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(3, 20, -2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-3, 20, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-2, 20, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 20, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 20, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 20, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(2, 20, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(3, 20, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-3, 20, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-2, 20, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 20, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 20, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(2, 20, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(3, 20, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-3, 20, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-2, 20, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 20, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 20, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 20, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(2, 20, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(3, 20, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-3, 20, 2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-2, 20, 2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 20, 2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 20, 2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 20, 2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(2, 20, 2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(3, 20, 2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-2, 20, 3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 20, 3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 20, 3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 20, 3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(2, 20, 3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 21, -2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 21, -2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 21, -2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-2, 21, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 21, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 21, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 21, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(2, 21, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-2, 21, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 21, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 21, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(2, 21, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-2, 21, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 21, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 21, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 21, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(2, 21, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 21, 2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 21, 2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 21, 2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-2, 22, -3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 22, -3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 22, -3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 22, -3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(2, 22, -3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-3, 22, -2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-2, 22, -2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 22, -2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 22, -2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 22, -2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(2, 22, -2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(3, 22, -2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-3, 22, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-2, 22, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 22, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 22, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 22, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(2, 22, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(3, 22, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-3, 22, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-2, 22, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 22, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 22, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(2, 22, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(3, 22, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-3, 22, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-2, 22, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 22, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 22, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 22, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(2, 22, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(3, 22, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-3, 22, 2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-2, 22, 2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 22, 2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 22, 2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 22, 2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(2, 22, 2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(3, 22, 2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-2, 22, 3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 22, 3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 22, 3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 22, 3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(2, 22, 3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 23, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 23, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 23, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 23, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 24, -3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-2, 24, -2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 24, -2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 24, -2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 24, -2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(2, 24, -2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-2, 24, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 24, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 24, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 24, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(2, 24, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-3, 24, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-2, 24, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 24, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 24, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(2, 24, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(3, 24, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-2, 24, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 24, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 24, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 24, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(2, 24, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-2, 24, 2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 24, 2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 24, 2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 24, 2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(2, 24, 2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 24, 3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 25, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 25, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 25, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 25, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 26, -2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 26, -2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 26, -2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-2, 26, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 26, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 26, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 26, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(2, 26, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-2, 26, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 26, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 26, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(2, 26, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-2, 26, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 26, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 26, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 26, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(2, 26, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 26, 2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 26, 2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 26, 2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 27, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 27, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 27, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 27, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 27, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 28, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 29, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 29, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 29, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 29, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 29, 1), boundsIn);
            }
        }
        return true;
    }

    //Log Placement
    private void treeLog(Set<BlockPos> setlogblock, IWorldGenerationReader reader, BlockPos pos, MutableBoundingBox boundingBox) {
        if (canTreePlaceHere(reader, pos)) {
            this.setFinalBlockState(setlogblock, reader, pos, BYGBlockList.PINE_LOG.getDefaultState(), boundingBox);
        }
    }

    //Log Placement
    private void treeBranch(Set<BlockPos> setlogblock, IWorldGenerationReader reader, BlockPos pos, MutableBoundingBox boundingBox) {
        if (canTreePlaceHere(reader, pos)) {
            this.setFinalBlockState(setlogblock, reader, pos, BYGBlockList.PINE_LOG.getDefaultState(), boundingBox);
        }
    }

    //Leaves Placement
    private void leafs(Set<BlockPos> blockPos, IWorldGenerationReader reader, BlockPos pos, MutableBoundingBox boundingBox) {
        BlockPos.Mutable blockpos = new BlockPos.Mutable(pos);
        if (isAir(reader, blockpos)) {
            this.setFinalBlockState(blockPos, reader, blockpos,  BYGBlockList.PINE_LEAVES.getDefaultState(), boundingBox);
        }
    }



    private boolean doesTreeFit(IWorldGenerationBaseReader reader, BlockPos blockPos, int height) {
        int x = blockPos.getX();
        int y = blockPos.getY();
        int z = blockPos.getZ();
        BlockPos.Mutable pos = new BlockPos.Mutable();

        for (int yOffset = 0; yOffset <= height + 1; ++yOffset) {
            //Distance/Density of trees. Positive Values ONLY
            int distance = 2;

            for (int xOffset = -distance; xOffset <= distance; ++xOffset) {
                for (int zOffset = -distance; zOffset <= distance; ++zOffset) {
                    if (!canTreePlaceHere(reader, pos.setPos(x + xOffset, y + yOffset, z + zOffset))) {
                        return false;
                    }
                }
            }
        }
        return true;
    }
}