package voronoiaoc.byg.common.world.feature.features.overworld.trees.pine;

import com.mojang.datafixers.Dynamic;
import net.minecraft.block.Blocks;
import net.minecraft.util.math.BlockPos;
import net.minecraft.util.math.MutableBoundingBox;
import net.minecraft.world.gen.IWorldGenerationBaseReader;
import net.minecraft.world.gen.IWorldGenerationReader;
import net.minecraft.world.gen.feature.NoFeatureConfig;
import voronoiaoc.byg.common.world.feature.features.overworld.trees.util.BYGAbstractTreeFeature;
import voronoiaoc.byg.core.byglists.BYGBlockList;

import java.util.Random;
import java.util.Set;
import java.util.function.Function;

public class LargePineTree2 extends BYGAbstractTreeFeature<NoFeatureConfig> {

    public LargePineTree2(Function<Dynamic<?>, ? extends NoFeatureConfig> configIn) {
        super(configIn);
    }

    protected boolean place(Set<BlockPos> changedBlocks, IWorldGenerationReader worldIn, Random rand, BlockPos pos, MutableBoundingBox boundsIn) {
        int randTreeHeight = 23 + rand.nextInt(5);
        BlockPos.Mutable mainmutable = new BlockPos.Mutable(pos);

        if (pos.getY() >= 1 && pos.getY() + randTreeHeight + 1 < worldIn.getMaxHeight()) {
            BlockPos blockpos = pos.down();
            if (!isDesiredGround(worldIn, blockpos, Blocks.GRASS_BLOCK)) {
                return false;
            } else if (!this.doesTreeFit(worldIn, pos, randTreeHeight)) {
                return false;
            } else {
                this.treeLog(changedBlocks, worldIn, mainmutable.add(0, 0, 0), boundsIn);
                this.treeLog(changedBlocks, worldIn, mainmutable.add(0, 1, 0), boundsIn);
                this.treeLog(changedBlocks, worldIn, mainmutable.add(0, 2, 0), boundsIn);
                this.treeLog(changedBlocks, worldIn, mainmutable.add(0, 3, 0), boundsIn);
                this.treeLog(changedBlocks, worldIn, mainmutable.add(0, 4, 0), boundsIn);
                this.treeLog(changedBlocks, worldIn, mainmutable.add(0, 5, 0), boundsIn);
                this.treeLog(changedBlocks, worldIn, mainmutable.add(0, 6, 0), boundsIn);
                this.treeLog(changedBlocks, worldIn, mainmutable.add(0, 7, 0), boundsIn);
                this.treeLog(changedBlocks, worldIn, mainmutable.add(0, 8, 0), boundsIn);
                this.treeLog(changedBlocks, worldIn, mainmutable.add(0, 9, 0), boundsIn);
                this.treeLog(changedBlocks, worldIn, mainmutable.add(0, 10, 0), boundsIn);
                this.treeLog(changedBlocks, worldIn, mainmutable.add(0, 11, 0), boundsIn);
                this.treeLog(changedBlocks, worldIn, mainmutable.add(0, 12, 0), boundsIn);
                this.treeLog(changedBlocks, worldIn, mainmutable.add(0, 13, 0), boundsIn);
                this.treeLog(changedBlocks, worldIn, mainmutable.add(0, 14, 0), boundsIn);
                this.treeLog(changedBlocks, worldIn, mainmutable.add(0, 15, 0), boundsIn);
                this.treeLog(changedBlocks, worldIn, mainmutable.add(0, 16, 0), boundsIn);
                this.treeLog(changedBlocks, worldIn, mainmutable.add(0, 17, 0), boundsIn);
                this.treeLog(changedBlocks, worldIn, mainmutable.add(0, 18, 0), boundsIn);
                this.treeLog(changedBlocks, worldIn, mainmutable.add(0, 19, 0), boundsIn);
                this.treeLog(changedBlocks, worldIn, mainmutable.add(0, 20, 0), boundsIn);
                this.treeLog(changedBlocks, worldIn, mainmutable.add(0, 21, 0), boundsIn);
                this.treeLog(changedBlocks, worldIn, mainmutable.add(0, 22, 0), boundsIn);
                this.treeLog(changedBlocks, worldIn, mainmutable.add(0, 23, 0), boundsIn);
                this.treeLog(changedBlocks, worldIn, mainmutable.add(0, 24, 0), boundsIn);
                this.treeLog(changedBlocks, worldIn, mainmutable.add(0, 25, 0), boundsIn);
                this.treeLog(changedBlocks, worldIn, mainmutable.add(0, 26, 0), boundsIn);
//                this.treeLog(changedBlocks, worldIn, mainmutable.add(0, 27, 0), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(3, 3, 0), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(0, 4, -3), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(-3, 4, 0), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(2, 4, 0), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(0, 5, -2), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(-2, 5, 0), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(1, 5, 0), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(0, 5, 3), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(0, 6, -1), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(-1, 6, 0), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(0, 6, 2), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(0, 7, 1), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(-3, 8, 0), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(3, 8, 0), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(0, 9, -3), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(-2, 9, 0), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(2, 9, 0), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(0, 9, 3), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(0, 10, -2), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(-1, 10, 0), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(1, 10, 0), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(0, 10, 2), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(0, 11, -1), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(0, 11, 1), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(0, 12, -3), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(0, 13, -2), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(-3, 13, 0), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(3, 13, 0), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(0, 14, -1), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(-2, 14, 0), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(2, 14, 0), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(0, 14, 3), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(-1, 15, 0), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(1, 15, 0), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(0, 15, 2), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(0, 16, 1), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(0, 17, -3), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(3, 17, 0), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(0, 18, -2), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(-3, 18, 0), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(2, 18, 0), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(0, 19, -1), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(-2, 19, 0), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(1, 19, 0), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(0, 19, 3), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(-1, 20, 0), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(0, 20, 2), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(0, 21, -2), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(2, 21, 0), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(0, 21, 1), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(0, 22, -1), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(-2, 22, 0), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(1, 22, 0), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(-1, 23, 0), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(0, 23, 2), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(0, 24, 1), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(0, 25, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(3, 2, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(4, 2, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 3, -4), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 3, -3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(3, 3, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(4, 3, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-4, 3, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-3, 3, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(4, 3, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(5, 3, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(3, 3, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(4, 3, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 4, -5), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 4, -4), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 4, -4), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 4, -4), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 4, -3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 4, -3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-4, 4, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-3, 4, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(2, 4, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(3, 4, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-5, 4, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-4, 4, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(3, 4, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(4, 4, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-4, 4, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-3, 4, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(2, 4, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(3, 4, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 4, 3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 4, 4), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 5, -4), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 5, -3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 5, -3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 5, -3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 5, -2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 5, -2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-3, 5, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-2, 5, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 5, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 5, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(2, 5, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-4, 5, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-3, 5, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(2, 5, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(3, 5, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-3, 5, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-2, 5, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 5, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(2, 5, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 5, 3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 5, 3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 5, 4), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 5, 4), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 5, 4), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 5, 5), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 6, -3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 6, -2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 6, -2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 6, -2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-2, 6, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 6, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 6, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-3, 6, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-2, 6, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 6, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-2, 6, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 6, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 6, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 6, 2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 6, 2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 6, 3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 6, 3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 6, 3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 6, 4), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-4, 7, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-3, 7, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 7, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(3, 7, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(4, 7, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 7, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 7, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 7, 2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 7, 2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 7, 2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 7, 3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 8, -4), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 8, -3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-4, 8, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-3, 8, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(3, 8, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(4, 8, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-5, 8, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-4, 8, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(4, 8, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(5, 8, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-4, 8, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-3, 8, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(3, 8, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(4, 8, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 8, 3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 8, 4), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 9, -5), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 9, -4), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 9, -4), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 9, -4), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 9, -3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 9, -3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-3, 9, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-2, 9, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(2, 9, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(3, 9, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-4, 9, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-3, 9, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(3, 9, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(4, 9, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-3, 9, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-2, 9, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(2, 9, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(3, 9, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 9, 3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 9, 3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 9, 4), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 9, 4), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 9, 4), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 9, 5), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 10, -4), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 10, -3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 10, -3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 10, -3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 10, -2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 10, -2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-2, 10, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 10, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 10, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 10, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(2, 10, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-3, 10, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-2, 10, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(2, 10, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(3, 10, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-2, 10, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 10, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 10, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 10, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(2, 10, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 10, 2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 10, 2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 10, 3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 10, 3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 10, 3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 10, 4), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 11, -4), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 11, -3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 11, -2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 11, -2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 11, -2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 11, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 11, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 11, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 11, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 11, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 11, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 11, 2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 11, 2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 11, 2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 11, 3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 12, -5), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 12, -4), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 12, -4), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 12, -4), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 12, -3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 12, -3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 12, -2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 12, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-4, 12, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-3, 12, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(3, 12, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(4, 12, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 13, -4), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 13, -3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 13, -3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 13, -3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 13, -2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 13, -2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-4, 13, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-3, 13, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 13, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(3, 13, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(4, 13, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-5, 13, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-4, 13, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(4, 13, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(5, 13, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-4, 13, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-3, 13, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(3, 13, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(4, 13, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 13, 3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 13, 4), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 14, -3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 14, -2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 14, -2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 14, -2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-3, 14, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-2, 14, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 14, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 14, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(2, 14, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(3, 14, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-4, 14, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-3, 14, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 14, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 14, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(3, 14, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(4, 14, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-3, 14, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-2, 14, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(2, 14, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(3, 14, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 14, 3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 14, 3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 14, 4), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 14, 4), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 14, 4), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 14, 5), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-2, 15, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 15, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 15, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 15, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(2, 15, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-3, 15, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-2, 15, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(2, 15, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(3, 15, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-2, 15, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 15, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 15, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 15, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(2, 15, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 15, 2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 15, 2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 15, 3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 15, 3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 15, 3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 15, 4), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 16, -4), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 16, -3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 16, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 16, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(3, 16, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(4, 16, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 16, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 16, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 16, 2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 16, 2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 16, 2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 16, 3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 17, -5), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 17, -4), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 17, -4), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 17, -4), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 17, -3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 17, -3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(3, 17, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(4, 17, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-4, 17, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-3, 17, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(4, 17, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(5, 17, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(3, 17, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(4, 17, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 18, -4), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 18, -3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 18, -3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 18, -3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 18, -2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 18, -2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-4, 18, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-3, 18, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(2, 18, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(3, 18, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-5, 18, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-4, 18, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(3, 18, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(4, 18, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-4, 18, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-3, 18, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(2, 18, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(3, 18, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 18, 3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 18, 4), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 19, -3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 19, -2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 19, -2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 19, -2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-3, 19, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-2, 19, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 19, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 19, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(2, 19, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-4, 19, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-3, 19, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 19, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(2, 19, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(3, 19, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-3, 19, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-2, 19, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 19, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(2, 19, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 19, 3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 19, 3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 19, 4), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 19, 4), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 19, 4), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 19, 5), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 20, -2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-2, 20, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 20, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 20, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-3, 20, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-2, 20, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 20, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(2, 20, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-2, 20, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 20, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 20, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 20, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 20, 2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 20, 2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 20, 3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 20, 3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 20, 3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 20, 4), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 21, -4), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 21, -3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 21, -3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 21, -3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 21, -2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 21, -2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 21, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(2, 21, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(3, 21, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-2, 21, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 21, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 21, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(3, 21, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(4, 21, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 21, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 21, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(2, 21, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(3, 21, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 21, 2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 21, 2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 21, 2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 21, 3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 22, -3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 22, -2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 22, -2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 22, -2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-3, 22, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-2, 22, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 22, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 22, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(2, 22, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-4, 22, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-3, 22, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 22, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(2, 22, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(3, 22, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-3, 22, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-2, 22, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 22, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 22, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(2, 22, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 22, 2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-2, 23, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 23, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 23, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-3, 23, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-2, 23, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 23, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-2, 23, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 23, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 23, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 23, 2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 23, 2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 23, 3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 23, 3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 23, 3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 23, 4), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 24, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 24, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 24, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 24, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 24, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 24, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 24, 2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 24, 2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 24, 2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 24, 3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 25, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 25, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 25, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 26, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 26, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 27, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 27, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 27, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 27, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 28, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 28, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 29, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 30, 0), boundsIn);
            }
        }
        return true;
    }

    //Log Placement
    private void treeLog(Set<BlockPos> setlogblock, IWorldGenerationReader reader, BlockPos pos, MutableBoundingBox boundingBox) {
        if (canTreePlaceHere(reader, pos)) {
            this.setFinalBlockState(setlogblock, reader, pos, BYGBlockList.PINE_LOG.getDefaultState(), boundingBox);
        }
    }

    //Log Placement
    private void treeBranch(Set<BlockPos> setlogblock, IWorldGenerationReader reader, BlockPos pos, MutableBoundingBox boundingBox) {
        if (canTreePlaceHere(reader, pos)) {
            this.setFinalBlockState(setlogblock, reader, pos, BYGBlockList.PINE_LOG.getDefaultState(), boundingBox);
        }
    }

    //Leaves Placement
    private void leafs(Set<BlockPos> blockPos, IWorldGenerationReader reader, BlockPos pos, MutableBoundingBox boundingBox) {
        BlockPos.Mutable blockpos = new BlockPos.Mutable(pos);
        if (isAir(reader, blockpos)) {
            this.setFinalBlockState(blockPos, reader, blockpos,  BYGBlockList.PINE_LEAVES.getDefaultState(), boundingBox);
        }
    }



    private boolean doesTreeFit(IWorldGenerationBaseReader reader, BlockPos blockPos, int height) {
        int x = blockPos.getX();
        int y = blockPos.getY();
        int z = blockPos.getZ();
        BlockPos.Mutable pos = new BlockPos.Mutable();

        for (int yOffset = 0; yOffset <= height + 1; ++yOffset) {
            //Distance/Density of trees. Positive Values ONLY
            int distance = 2;

            for (int xOffset = -distance; xOffset <= distance; ++xOffset) {
                for (int zOffset = -distance; zOffset <= distance; ++zOffset) {
                    if (!canTreePlaceHere(reader, pos.setPos(x + xOffset, y + yOffset, z + zOffset))) {
                        return false;
                    }
                }
            }
        }
        return true;
    }
}