package corgiaoc.byg.core.world;

import corgiaoc.byg.common.world.surfacebuilder.config.FillSurfaceBuilderConfig;
import corgiaoc.byg.common.world.surfacebuilder.config.PointedSBConfig;
import corgiaoc.byg.core.BYGBlocks;
import corgiaoc.byg.core.world.util.WorldGenRegistrationHelper;
import net.minecraft.util.random.SimpleWeightedRandomList;
import net.minecraft.world.level.block.Blocks;
import net.minecraft.world.level.block.state.BlockState;
import net.minecraft.world.level.levelgen.feature.stateproviders.SimpleStateProvider;
import net.minecraft.world.level.levelgen.feature.stateproviders.WeightedStateProvider;
import net.minecraft.world.level.levelgen.surfacebuilders.ConfiguredSurfaceBuilder;
import net.minecraft.world.level.levelgen.surfacebuilders.SurfaceBuilder;
import net.minecraft.world.level.levelgen.surfacebuilders.SurfaceBuilderBaseConfiguration;

public class BYGConfiguredSurfaceBuilders {

    public static final ConfiguredSurfaceBuilder<?> BASALT_BARRERA = WorldGenRegistrationHelper.createConfiguredSurfaceBuilder("basalt_barrera", new ConfiguredSurfaceBuilder<>(BYGSurfaceBuilders.BASALT_BARRERA, BYGSurfaceBuilders.Configs.BLACK_SAND));
    public static final ConfiguredSurfaceBuilder<?> BLACK_FOREST = WorldGenRegistrationHelper.createConfiguredSurfaceBuilder("black_forest", new ConfiguredSurfaceBuilder<>(BYGSurfaceBuilders.CONIFEROUS, BYGSurfaceBuilders.Configs.PEATGRASS_CF));
    public static final ConfiguredSurfaceBuilder<?> BLACK_SAND = WorldGenRegistrationHelper.createConfiguredSurfaceBuilder("black_sand", new ConfiguredSurfaceBuilder<>(SurfaceBuilder.DEFAULT, BYGSurfaceBuilders.Configs.BLACK_SAND));
    public static final ConfiguredSurfaceBuilder<?> BOREAL_FOREST = WorldGenRegistrationHelper.createConfiguredSurfaceBuilder("boreal_forest", new ConfiguredSurfaceBuilder<>(BYGSurfaceBuilders.BOREAL, SurfaceBuilder.CONFIG_GRASS));
    public static final ConfiguredSurfaceBuilder<?> CRAG_GARDENS = WorldGenRegistrationHelper.createConfiguredSurfaceBuilder("crag_gardens", new ConfiguredSurfaceBuilder<>(BYGSurfaceBuilders.CRAG_GARDENS, BYGSurfaceBuilders.Configs.GREEN_CONCRETE_POWDER_CF));
    public static final ConfiguredSurfaceBuilder<?> EBONY_WOODS = WorldGenRegistrationHelper.createConfiguredSurfaceBuilder("ebony_woods", new ConfiguredSurfaceBuilder<>(BYGSurfaceBuilders.EBONY, SurfaceBuilder.CONFIG_GRASS));
    public static final ConfiguredSurfaceBuilder<?> FILL_DACITE_PODZOL = WorldGenRegistrationHelper.createConfiguredSurfaceBuilder("fill_dacite", new ConfiguredSurfaceBuilder<>(BYGSurfaceBuilders.FILL, new FillSurfaceBuilderConfig.Builder().setFillBlock(Blocks.SAND).setTopBlock(BYGBlocks.PODZOL_DACITE).setUnderBlock(BYGBlocks.DACITE).setFillDownToY(63).build()));
    public static final ConfiguredSurfaceBuilder<?> FILL_SAND = WorldGenRegistrationHelper.createConfiguredSurfaceBuilder("fill_sand", new ConfiguredSurfaceBuilder<>(BYGSurfaceBuilders.FILL, new FillSurfaceBuilderConfig.Builder().setFillBlock(Blocks.SAND).setTopBlock(Blocks.SAND).setUnderBlock(Blocks.SAND).setFillDownToY(63).build()));
    public static final ConfiguredSurfaceBuilder<?> FILL_SAND_RED = WorldGenRegistrationHelper.createConfiguredSurfaceBuilder("fill_sand_red", new ConfiguredSurfaceBuilder<>(BYGSurfaceBuilders.FILL, new FillSurfaceBuilderConfig.Builder().setFillBlock(Blocks.RED_SAND).setTopBlock(Blocks.RED_SAND).setUnderBlock(Blocks.RED_SAND).setFillDownToY(63).build()));
    public static final ConfiguredSurfaceBuilder<?> GLOWING_ANCIENT_FOREST = WorldGenRegistrationHelper.createConfiguredSurfaceBuilder("glowing_ancient_forest", new ConfiguredSurfaceBuilder<>(BYGSurfaceBuilders.GLOWING_ANCIENT_FOREST, SurfaceBuilder.CONFIG_GRASS));
    public static final ConfiguredSurfaceBuilder<?> GREAT_LAKE_ISLES = WorldGenRegistrationHelper.createConfiguredSurfaceBuilder("great_lake_isles", new ConfiguredSurfaceBuilder<>(BYGSurfaceBuilders.GREAT_LAKE_ISLES, SurfaceBuilder.CONFIG_GRASS));
    public static final ConfiguredSurfaceBuilder<?> LUSH_TUNDRA = WorldGenRegistrationHelper.createConfiguredSurfaceBuilder("lush_tundra", new ConfiguredSurfaceBuilder<>(BYGSurfaceBuilders.LUSH_TUNDRA, SurfaceBuilder.CONFIG_GRASS));
    public static final ConfiguredSurfaceBuilder<?> MOJAVE = WorldGenRegistrationHelper.createConfiguredSurfaceBuilder("mojave", new ConfiguredSurfaceBuilder<>(BYGSurfaceBuilders.MOJAVE, new SurfaceBuilderBaseConfiguration(Blocks.SAND.defaultBlockState(), Blocks.SAND.defaultBlockState(), Blocks.SANDSTONE.defaultBlockState())));
    public static final ConfiguredSurfaceBuilder<?> MARSHLAND = WorldGenRegistrationHelper.createConfiguredSurfaceBuilder("marshland", new ConfiguredSurfaceBuilder<>(BYGSurfaceBuilders.MARSHLAND, new SurfaceBuilderBaseConfiguration(Blocks.GRASS_BLOCK.defaultBlockState(), Blocks.DIRT.defaultBlockState(), BYGBlocks.MUD_BLOCK.defaultBlockState())));
    public static final ConfiguredSurfaceBuilder<?> MEADOW = WorldGenRegistrationHelper.createConfiguredSurfaceBuilder("meadow", new ConfiguredSurfaceBuilder<>(SurfaceBuilder.DEFAULT, new SurfaceBuilderBaseConfiguration(BYGBlocks.LUSH_GRASS_BLOCK.defaultBlockState(), BYGBlocks.LUSH_DIRT.defaultBlockState(), BYGBlocks.LUSH_DIRT.defaultBlockState())));
    public static final ConfiguredSurfaceBuilder<?> OVERGROWN_STONE = WorldGenRegistrationHelper.createConfiguredSurfaceBuilder("overgrown_stone", new ConfiguredSurfaceBuilder<>(SurfaceBuilder.DEFAULT, new SurfaceBuilderBaseConfiguration(BYGBlocks.OVERGROWN_STONE.defaultBlockState(), Blocks.STONE.defaultBlockState(), Blocks.STONE.defaultBlockState())));
    public static final ConfiguredSurfaceBuilder<?> PEAT_GRASS = WorldGenRegistrationHelper.createConfiguredSurfaceBuilder("peat_grass", new ConfiguredSurfaceBuilder<>(BYGSurfaceBuilders.CONIFEROUS, BYGSurfaceBuilders.Configs.PEATGRASS_CF));
    public static final ConfiguredSurfaceBuilder<?> RAINBOW_BEACH = WorldGenRegistrationHelper.createConfiguredSurfaceBuilder("rainbow_beach", new ConfiguredSurfaceBuilder<>(BYGSurfaceBuilders.RAINBOW_BEACH, BYGSurfaceBuilders.Configs.PURPLE_SAND));
    public static final ConfiguredSurfaceBuilder<?> RED_SAND = WorldGenRegistrationHelper.createConfiguredSurfaceBuilder("red_sand", new ConfiguredSurfaceBuilder<>(SurfaceBuilder.DEFAULT, new SurfaceBuilderBaseConfiguration(Blocks.RED_SAND.defaultBlockState(), Blocks.RED_SAND.defaultBlockState(), Blocks.RED_SANDSTONE.defaultBlockState())));
    public static final ConfiguredSurfaceBuilder<?> RED_ROCK = WorldGenRegistrationHelper.createConfiguredSurfaceBuilder("red_rock", new ConfiguredSurfaceBuilder<>(BYGSurfaceBuilders.RED_ROCK_SB, SurfaceBuilder.CONFIG_GRASS));
    public static final ConfiguredSurfaceBuilder<?> ROCKY_BLACK_BEACH = WorldGenRegistrationHelper.createConfiguredSurfaceBuilder("rocky_black_beach", new ConfiguredSurfaceBuilder<>(BYGSurfaceBuilders.ROCKY_BLACK_BEACH, BYGSurfaceBuilders.Configs.BLACK_SAND));
    public static final ConfiguredSurfaceBuilder<?> SHATTERED_GLACIER = WorldGenRegistrationHelper.createConfiguredSurfaceBuilder("shattered_glacier", new ConfiguredSurfaceBuilder<>(BYGSurfaceBuilders.SHATTERED_GLACIER, new SurfaceBuilderBaseConfiguration(Blocks.SNOW_BLOCK.defaultBlockState(), Blocks.SNOW_BLOCK.defaultBlockState(), Blocks.SNOW_BLOCK.defaultBlockState())));
    public static final ConfiguredSurfaceBuilder<?> SIERRA_VALLEY = WorldGenRegistrationHelper.createConfiguredSurfaceBuilder("sierra_valley", new ConfiguredSurfaceBuilder<>(BYGSurfaceBuilders.SIERRA_VALLEY, SurfaceBuilder.CONFIG_GRASS));
    public static final ConfiguredSurfaceBuilder<?> STONE_FOREST = WorldGenRegistrationHelper.createConfiguredSurfaceBuilder("stone_forest", new ConfiguredSurfaceBuilder<>(BYGSurfaceBuilders.STONE_FOREST, new SurfaceBuilderBaseConfiguration(BYGBlocks.OVERGROWN_STONE.defaultBlockState(), Blocks.STONE.defaultBlockState(), Blocks.STONE.defaultBlockState())));
    public static final ConfiguredSurfaceBuilder<?> STONE_FOREST_POINTED = WorldGenRegistrationHelper.createConfiguredSurfaceBuilder("pointed_stone_forest", new ConfiguredSurfaceBuilder<>(BYGSurfaceBuilders.POINTED, new PointedSBConfig(BYGBlocks.OVERGROWN_STONE.defaultBlockState(), Blocks.STONE.defaultBlockState(), new WeightedStateProvider(SimpleWeightedRandomList.<BlockState>builder().add(Blocks.STONE.defaultBlockState(), 3).add(Blocks.STONE.defaultBlockState(), 2)), new SimpleStateProvider(BYGBlocks.OVERGROWN_STONE.defaultBlockState()), 170)));
    public static final ConfiguredSurfaceBuilder<?> TWILIGHT_VALLEY = WorldGenRegistrationHelper.createConfiguredSurfaceBuilder("twilight_valley", new ConfiguredSurfaceBuilder<>(BYGSurfaceBuilders.TWILIGHT_VALLEY, SurfaceBuilder.CONFIG_GRASS));
    public static final ConfiguredSurfaceBuilder<?> WHITE_SAND = WorldGenRegistrationHelper.createConfiguredSurfaceBuilder("white_sand", new ConfiguredSurfaceBuilder<>(SurfaceBuilder.DEFAULT, BYGSurfaceBuilders.Configs.WHITE_SAND));

    //nether
    public static final ConfiguredSurfaceBuilder<?> BRIMSTONE_CAVERNS = WorldGenRegistrationHelper.createConfiguredSurfaceBuilder("brimstone_caverns", new ConfiguredSurfaceBuilder<>(BYGSurfaceBuilders.BRIMSTONE_CAVERNS, BYGSurfaceBuilders.Configs.BRIMSTONE));
    public static final ConfiguredSurfaceBuilder<?> CRIMSON_GARDENS = WorldGenRegistrationHelper.createConfiguredSurfaceBuilder("crimson_gardens", new ConfiguredSurfaceBuilder<>(BYGSurfaceBuilders.CRIMSON_GARDENS, BYGSurfaceBuilders.Configs.CRIMSON_GARDEN));
    public static final ConfiguredSurfaceBuilder<?> EMBUR_BOG = WorldGenRegistrationHelper.createConfiguredSurfaceBuilder("embur_bog", new ConfiguredSurfaceBuilder<>(BYGSurfaceBuilders.EMBUR_BOG, BYGSurfaceBuilders.Configs.EMBURNYLIUM));
    public static final ConfiguredSurfaceBuilder<?> GLOWSTONE_GARDENS = WorldGenRegistrationHelper.createConfiguredSurfaceBuilder("glowstone_gardens", new ConfiguredSurfaceBuilder<>(BYGSurfaceBuilders.GLOWSTONE_GARDENS, BYGSurfaceBuilders.Configs.GLOWSTONE_GARDENS));
    public static final ConfiguredSurfaceBuilder<?> QUARTZ_DESERT = WorldGenRegistrationHelper.createConfiguredSurfaceBuilder("quartz_desert", new ConfiguredSurfaceBuilder<>(BYGSurfaceBuilders.QUARTZ_DESERT, BYGSurfaceBuilders.Configs.WARPEDDESERT));
    public static final ConfiguredSurfaceBuilder<?> SUBZERO_HYPOGEAL = WorldGenRegistrationHelper.createConfiguredSurfaceBuilder("subzero_hypogeal", new ConfiguredSurfaceBuilder<>(BYGSurfaceBuilders.SUBZERO_HYPOGEAL, BYGSurfaceBuilders.Configs.FROST_MAGMA));
    public static final ConfiguredSurfaceBuilder<?> SYTHIAN_TORRIDS = WorldGenRegistrationHelper.createConfiguredSurfaceBuilder("sythian_torrids", new ConfiguredSurfaceBuilder<>(SurfaceBuilder.DEFAULT, BYGSurfaceBuilders.Configs.SYTHIANTORRIDS));
    public static final ConfiguredSurfaceBuilder<?> WARPED_DESERT = WorldGenRegistrationHelper.createConfiguredSurfaceBuilder("warped_desert", new ConfiguredSurfaceBuilder<>(BYGSurfaceBuilders.WARPED_DESERT, BYGSurfaceBuilders.Configs.WARPEDDESERT));
    public static final ConfiguredSurfaceBuilder<?> WAILING_GARTH = WorldGenRegistrationHelper.createConfiguredSurfaceBuilder("wailing_garth", new ConfiguredSurfaceBuilder<>(BYGSurfaceBuilders.WAILING_GARTH, BYGSurfaceBuilders.Configs.SOULSAND));
    public static final ConfiguredSurfaceBuilder<?> WITHERING_WOODS = WorldGenRegistrationHelper.createConfiguredSurfaceBuilder("withering_woods", new ConfiguredSurfaceBuilder<>(BYGSurfaceBuilders.WITHERING_WOODS, BYGSurfaceBuilders.Configs.MAGMATIC_STONE));
    public static final ConfiguredSurfaceBuilder<?> WEEPING_MIRE = WorldGenRegistrationHelper.createConfiguredSurfaceBuilder("weeping_mire", new ConfiguredSurfaceBuilder<>(BYGSurfaceBuilders.WEEPING_MIRE, BYGSurfaceBuilders.Configs.SOULSAND));

    //end
    public static final ConfiguredSurfaceBuilder<?> BULBIS_GARDENS = WorldGenRegistrationHelper.createConfiguredSurfaceBuilder("bulbis_gardens", new ConfiguredSurfaceBuilder<>(BYGSurfaceBuilders.BULBIS_GARDENS, BYGSurfaceBuilders.Configs.BULBIS_PHYCELIUM_CF));
    public static final ConfiguredSurfaceBuilder<?> BULBIS_GARDENS_EDGE = WorldGenRegistrationHelper.createConfiguredSurfaceBuilder("bulbis_gardens_edge", new ConfiguredSurfaceBuilder<>(BYGSurfaceBuilders.BULBIS_GARDENS, BYGSurfaceBuilders.Configs.BULBIS_PHYCELIUM_CF));
    public static final ConfiguredSurfaceBuilder<?> CRYPTIC_WASTES = WorldGenRegistrationHelper.createConfiguredSurfaceBuilder("cryptic_wastes", new ConfiguredSurfaceBuilder<>(BYGSurfaceBuilders.CRYPTIC, BYGSurfaceBuilders.Configs.CRYPTIC));
    public static final ConfiguredSurfaceBuilder<?> ETHEREAL_ISLANDS = WorldGenRegistrationHelper.createConfiguredSurfaceBuilder("ethereal_islands", new ConfiguredSurfaceBuilder<>(BYGSurfaceBuilders.ETHEREAL, BYGSurfaceBuilders.Configs.ETHER));
    public static final ConfiguredSurfaceBuilder<?> ETHEREAL_CLEARING = WorldGenRegistrationHelper.createConfiguredSurfaceBuilder("ethereal_clearing", new ConfiguredSurfaceBuilder<>(BYGSurfaceBuilders.ETHEREAL, BYGSurfaceBuilders.Configs.ETHER));
    public static final ConfiguredSurfaceBuilder<?> ETHEREAL_FOREST = WorldGenRegistrationHelper.createConfiguredSurfaceBuilder("ethereal_forest", new ConfiguredSurfaceBuilder<>(BYGSurfaceBuilders.ETHEREAL, BYGSurfaceBuilders.Configs.ETHER));
    public static final ConfiguredSurfaceBuilder<?> IMPARIUS_GROVE = WorldGenRegistrationHelper.createConfiguredSurfaceBuilder("imparius_grove", new ConfiguredSurfaceBuilder<>(SurfaceBuilder.DEFAULT, BYGSurfaceBuilders.Configs.IMPARIUS));
    public static final ConfiguredSurfaceBuilder<?> IMPARIUS_CLEARING = WorldGenRegistrationHelper.createConfiguredSurfaceBuilder("imparius_clearing", new ConfiguredSurfaceBuilder<>(SurfaceBuilder.DEFAULT, BYGSurfaceBuilders.Configs.IMPARIUS));
    public static final ConfiguredSurfaceBuilder<?> IVIS_FIELDS = WorldGenRegistrationHelper.createConfiguredSurfaceBuilder("ivis_fields", new ConfiguredSurfaceBuilder<>(BYGSurfaceBuilders.IVIS_FIELDS, BYGSurfaceBuilders.Configs.END));
    public static final ConfiguredSurfaceBuilder<?> NIGHTSHADE_FOREST = WorldGenRegistrationHelper.createConfiguredSurfaceBuilder("nightshade_forest", new ConfiguredSurfaceBuilder<>(SurfaceBuilder.DEFAULT, BYGSurfaceBuilders.Configs.NIGHTSHADE));
    public static final ConfiguredSurfaceBuilder<?> PURPUR_PEAKS = WorldGenRegistrationHelper.createConfiguredSurfaceBuilder("purpur_peaks", new ConfiguredSurfaceBuilder<>(BYGSurfaceBuilders.PURPUR_PEAKS, BYGSurfaceBuilders.Configs.END));
    public static final ConfiguredSurfaceBuilder<?> SHATTERED_DESERT = WorldGenRegistrationHelper.createConfiguredSurfaceBuilder("shattered_desert", new ConfiguredSurfaceBuilder<>(BYGSurfaceBuilders.SHATTERED_DESERT, BYGSurfaceBuilders.Configs.END));
    public static final ConfiguredSurfaceBuilder<?> SHATTERED_DESERT_ISLES = WorldGenRegistrationHelper.createConfiguredSurfaceBuilder("shattered_desert_isles", new ConfiguredSurfaceBuilder<>(BYGSurfaceBuilders.SHATTERED_DESERT, BYGSurfaceBuilders.Configs.END));
    public static final ConfiguredSurfaceBuilder<?> SHULKREN_FOREST = WorldGenRegistrationHelper.createConfiguredSurfaceBuilder("shulkren_forest", new ConfiguredSurfaceBuilder<>(SurfaceBuilder.DEFAULT, BYGSurfaceBuilders.Configs.SHULKREN));
    public static final ConfiguredSurfaceBuilder<?> VISCALISLES = WorldGenRegistrationHelper.createConfiguredSurfaceBuilder("shattered_viscal_isles", new ConfiguredSurfaceBuilder<>(BYGSurfaceBuilders.ETHEREAL, BYGSurfaceBuilders.Configs.SCULK));
    public static final ConfiguredSurfaceBuilder<?> SHATTERED_VISCAL_ISLES = WorldGenRegistrationHelper.createConfiguredSurfaceBuilder("viscal_isles", new ConfiguredSurfaceBuilder<>(BYGSurfaceBuilders.ETHEREAL, BYGSurfaceBuilders.Configs.SCULK));

}
