package corgiaoc.byg.common.world.feature.end.trees.bulbis;

import com.mojang.serialization.Codec;
import corgiaoc.byg.common.world.feature.config.BYGMushroomConfig;
import corgiaoc.byg.common.world.feature.overworld.mushrooms.util.BYGAbstractMushroomFeature;
import corgiaoc.byg.core.BYGBlocks;
import net.minecraft.block.BlockState;
import net.minecraft.util.math.BlockPos;
import net.minecraft.world.ISeedReader;

import java.util.Random;

public class BulbisTree3 extends BYGAbstractMushroomFeature<BYGMushroomConfig> {

    public BulbisTree3(Codec<BYGMushroomConfig> configIn) {
        super(configIn);
    }

    protected boolean placeMushroom(ISeedReader worldIn, Random rand, BlockPos pos, boolean isMushroom, BYGMushroomConfig config) {
        BlockState STEM = config.getStemProvider().getBlockState(rand, pos);
        BlockState MUSHROOM = config.getMushroomProvider().getBlockState(rand, pos);
        BlockState MUSHROOM2 = config.getMushroom2Provider().getBlockState(rand, pos);
        BlockState MUSHROOM3 = config.getMushroom3Provider().getBlockState(rand, pos);
        BlockState POLLEN = config.getPollenProvider().getBlockState(rand, pos);
        int randTreeHeight = 8 + rand.nextInt(5);
        BlockPos.Mutable mainmutable = new BlockPos.Mutable().setPos(pos);

        if (pos.getY() + randTreeHeight + 1 < worldIn.getHeight()) {
            if (!isDesiredGroundwEndTags(config, worldIn, pos.down(), BYGBlocks.IVIS_PHYLIUM)) {
                return false;
            } else if (!this.isAnotherMushroomLikeThisNearby(worldIn, pos, randTreeHeight, 0, STEM.getBlock(), MUSHROOM.getBlock(), isMushroom)) {
                return false;
            } else if (!this.doesMushroomHaveSpaceToGrow(worldIn, pos, randTreeHeight, 5, 5, 5, isMushroom)) {
                return false;
            } else {
                placeStem(STEM, worldIn, mainmutable.setPos(pos).move(0, 0, 0));
                placeStem(STEM, worldIn, mainmutable.setPos(pos).move(0, 1, 0));
                placeStem(STEM, worldIn, mainmutable.setPos(pos).move(0, 2, 0));
                placeStem(STEM, worldIn, mainmutable.setPos(pos).move(0, 3, 0));
                placeStem(STEM, worldIn, mainmutable.setPos(pos).move(0, 4, 0));
                placeStem(STEM, worldIn, mainmutable.setPos(pos).move(0, 5, 0));
                placeStem(STEM, worldIn, mainmutable.setPos(pos).move(0, 6, 0));
                placeStem(STEM, worldIn, mainmutable.setPos(pos).move(0, 7, 0));
                placeStem(STEM, worldIn, mainmutable.setPos(pos).move(0, 8, 0));
                placeStem(STEM, worldIn, mainmutable.setPos(pos).move(0, 9, 0));
                placeStem(STEM, worldIn, mainmutable.setPos(pos).move(0, 10, 0));
                placeStemBranch(STEM, worldIn, mainmutable.setPos(pos).move(-1, 5, -1));
                placeStemBranch(STEM, worldIn, mainmutable.setPos(pos).move(-1, 6, -1));
                placeStemBranch(STEM, worldIn, mainmutable.setPos(pos).move(-2, 7, -2));
                placeStemBranch(STEM, worldIn, mainmutable.setPos(pos).move(0, 10, -1));
                placeStemBranch(STEM, worldIn, mainmutable.setPos(pos).move(1, 10, 1));
                placeStemBranch(STEM, worldIn, mainmutable.setPos(pos).move(0, 11, -1));
                placeStemBranch(STEM, worldIn, mainmutable.setPos(pos).move(1, 11, 1));
                placeStemBranch(STEM, worldIn, mainmutable.setPos(pos).move(-1, 12, -2));
                placeStemBranch(STEM, worldIn, mainmutable.setPos(pos).move(0, 12, -1));
                placeStemBranch(STEM, worldIn, mainmutable.setPos(pos).move(1, 12, 1));
                placeStemBranch(STEM, worldIn, mainmutable.setPos(pos).move(-1, 13, -3));
                placeStemBranch(STEM, worldIn, mainmutable.setPos(pos).move(-1, 13, -2));
                placeStemBranch(STEM, worldIn, mainmutable.setPos(pos).move(0, 13, -3));
                placeStemBranch(STEM, worldIn, mainmutable.setPos(pos).move(1, 13, 1));
                placeStemBranch(STEM, worldIn, mainmutable.setPos(pos).move(0, 14, -3));
                placeStemBranch(STEM, worldIn, mainmutable.setPos(pos).move(1, 14, 1));
                placeStemBranch(STEM, worldIn, mainmutable.setPos(pos).move(1, 14, 2));
                placeStemBranch(STEM, worldIn, mainmutable.setPos(pos).move(0, 15, -3));
                placeStemBranch(STEM, worldIn, mainmutable.setPos(pos).move(1, 15, 2));
                placeStemBranch(STEM, worldIn, mainmutable.setPos(pos).move(2, 15, 3));
                placeStemBranch(STEM, worldIn, mainmutable.setPos(pos).move(2, 16, 3));
                placeStemBranch(STEM, worldIn, mainmutable.setPos(pos).move(2, 17, 3));
                placeStemBranch(STEM, worldIn, mainmutable.setPos(pos).move(2, 18, 3));
                placeStemBranch(STEM, worldIn, mainmutable.setPos(pos).move(2, 19, 3));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(-2, 5, -2));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(-3, 6, -3));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(-3, 6, -2));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(-3, 6, -1));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(-2, 6, -3));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(-2, 6, -2));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(-2, 6, -1));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(-1, 6, -3));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(-1, 6, -2));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(-4, 7, -2));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(-3, 7, -3));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(-3, 7, -2));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(-3, 7, -1));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(-2, 7, -4));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(-2, 7, -3));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(-2, 7, -1));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(-2, 7, 0));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(-1, 7, -3));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(-1, 7, -2));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(-1, 7, -1));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(0, 7, -2));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(-3, 8, -3));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(-3, 8, -2));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(-3, 8, -1));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(-2, 8, -3));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(-2, 8, -2));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(-2, 8, -1));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(-1, 8, -3));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(-1, 8, -2));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(-1, 8, -1));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(-2, 9, -2));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(-1, 15, -4));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(-1, 15, -3));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(-1, 15, -2));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(0, 15, -4));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(0, 15, -2));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(1, 15, -4));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(1, 15, -3));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(1, 15, -2));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(-2, 16, -5));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(-2, 16, -4));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(-2, 16, -3));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(-2, 16, -2));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(-2, 16, -1));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(-1, 16, -5));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(-1, 16, -4));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(-1, 16, -3));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(-1, 16, -2));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(-1, 16, -1));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(0, 16, -5));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(0, 16, -4));
                this.shroomlight(worldIn, mainmutable.setPos(pos).move(0, 16, -3));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(0, 16, -2));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(0, 16, -1));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(1, 16, -5));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(1, 16, -4));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(1, 16, -3));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(1, 16, -2));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(1, 16, -1));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(2, 16, -5));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(2, 16, -4));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(2, 16, -3));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(2, 16, -2));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(2, 16, -1));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(-3, 17, -4));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(-3, 17, -3));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(-3, 17, -2));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(-2, 17, -5));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(-2, 17, -4));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(-2, 17, -3));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(-2, 17, -2));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(-2, 17, -1));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(-1, 17, -6));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(-1, 17, -5));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(-1, 17, -4));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(-1, 17, -2));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(-1, 17, -1));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(-1, 17, 0));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(0, 17, -6));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(0, 17, -5));
                this.shroomlight(worldIn, mainmutable.setPos(pos).move(0, 17, -4));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(0, 17, -1));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(0, 17, 0));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(1, 17, -6));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(1, 17, -5));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(1, 17, -4));
                this.shroomlight(worldIn, mainmutable.setPos(pos).move(1, 17, -3));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(1, 17, -2));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(1, 17, -1));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(1, 17, 0));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(2, 17, -5));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(2, 17, -4));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(2, 17, -3));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(2, 17, -2));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(2, 17, -1));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(3, 17, -4));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(3, 17, -3));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(3, 17, -2));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(-3, 18, -4));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(-3, 18, -3));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(-3, 18, -2));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(-2, 18, -5));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(-2, 18, -4));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(-2, 18, -3));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(-2, 18, -2));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(-2, 18, -1));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(-1, 18, -6));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(-1, 18, -5));
                this.shroomlight(worldIn, mainmutable.setPos(pos).move(-1, 18, -3));
                this.shroomlight(worldIn, mainmutable.setPos(pos).move(-1, 18, -2));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(-1, 18, -1));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(-1, 18, 0));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(0, 18, -6));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(0, 18, -5));
                this.shroomlight(worldIn, mainmutable.setPos(pos).move(0, 18, -4));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(0, 18, -1));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(0, 18, 0));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(1, 18, -6));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(1, 18, -5));
                this.shroomlight(worldIn, mainmutable.setPos(pos).move(1, 18, -4));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(1, 18, -1));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(1, 18, 0));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(2, 18, -5));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(2, 18, -4));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(2, 18, -3));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(2, 18, -2));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(2, 18, -1));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(3, 18, -4));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(3, 18, -3));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(3, 18, -2));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(-3, 19, -4));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(-3, 19, -3));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(-3, 19, -2));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(-2, 19, -5));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(-2, 19, -4));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(-2, 19, -3));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(-2, 19, -2));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(-2, 19, -1));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(-1, 19, -6));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(-1, 19, -5));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(-1, 19, -4));
                this.shroomlight(worldIn, mainmutable.setPos(pos).move(-1, 19, -3));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(-1, 19, -2));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(-1, 19, -1));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(-1, 19, 0));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(0, 19, -6));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(0, 19, -5));
                this.shroomlight(worldIn, mainmutable.setPos(pos).move(0, 19, -2));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(0, 19, -1));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(0, 19, 0));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(1, 19, -6));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(1, 19, -5));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(1, 19, -4));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(1, 19, -2));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(1, 19, -1));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(1, 19, 0));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(1, 19, 2));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(1, 19, 3));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(1, 19, 4));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(2, 19, -5));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(2, 19, -4));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(2, 19, -3));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(2, 19, -2));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(2, 19, -1));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(2, 19, 2));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(2, 19, 4));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(3, 19, -4));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(3, 19, -3));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(3, 19, -2));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(3, 19, 2));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(3, 19, 3));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(3, 19, 4));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(-2, 20, -5));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(-2, 20, -4));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(-2, 20, -3));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(-2, 20, -2));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(-2, 20, -1));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(-1, 20, -5));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(-1, 20, -4));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(-1, 20, -3));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(-1, 20, -2));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(-1, 20, -1));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(0, 20, -5));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(0, 20, -4));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(0, 20, -3));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(0, 20, -2));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(0, 20, -1));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(0, 20, 1));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(0, 20, 2));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(0, 20, 3));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(0, 20, 4));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(0, 20, 5));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(1, 20, -5));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(1, 20, -4));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(1, 20, -3));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(1, 20, -2));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(1, 20, -1));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(1, 20, 1));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(1, 20, 2));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(1, 20, 3));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(1, 20, 4));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(1, 20, 5));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(2, 20, -5));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(2, 20, -4));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(2, 20, -3));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(2, 20, -2));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(2, 20, -1));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(2, 20, 1));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(2, 20, 2));
                this.shroomlight(worldIn, mainmutable.setPos(pos).move(2, 20, 3));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(2, 20, 4));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(2, 20, 5));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(3, 20, 1));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(3, 20, 2));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(3, 20, 3));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(3, 20, 4));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(3, 20, 5));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(4, 20, 1));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(4, 20, 2));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(4, 20, 3));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(4, 20, 4));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(4, 20, 5));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(-1, 21, -4));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(-1, 21, -3));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(-1, 21, -2));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(-1, 21, 2));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(-1, 21, 3));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(-1, 21, 4));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(0, 21, -4));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(0, 21, -3));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(0, 21, -2));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(0, 21, 1));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(0, 21, 2));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(0, 21, 3));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(0, 21, 4));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(0, 21, 5));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(1, 21, -4));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(1, 21, -3));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(1, 21, -2));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(1, 21, 0));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(1, 21, 1));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(1, 21, 2));
                this.shroomlight(worldIn, mainmutable.setPos(pos).move(1, 21, 3));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(1, 21, 4));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(1, 21, 5));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(1, 21, 6));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(2, 21, 0));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(2, 21, 1));
                this.shroomlight(worldIn, mainmutable.setPos(pos).move(2, 21, 4));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(2, 21, 5));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(2, 21, 6));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(3, 21, 0));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(3, 21, 1));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(3, 21, 2));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(3, 21, 4));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(3, 21, 5));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(3, 21, 6));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(4, 21, 1));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(4, 21, 2));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(4, 21, 3));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(4, 21, 4));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(4, 21, 5));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(5, 21, 2));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(5, 21, 3));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(5, 21, 4));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(-1, 22, 2));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(-1, 22, 3));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(-1, 22, 4));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(0, 22, 1));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(0, 22, 2));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(0, 22, 3));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(0, 22, 4));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(0, 22, 5));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(1, 22, 0));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(1, 22, 1));
                this.shroomlight(worldIn, mainmutable.setPos(pos).move(1, 22, 3));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(1, 22, 5));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(1, 22, 6));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(2, 22, 0));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(2, 22, 1));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(2, 22, 5));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(2, 22, 6));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(3, 22, 0));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(3, 22, 1));
                this.shroomlight(worldIn, mainmutable.setPos(pos).move(3, 22, 2));
                this.shroomlight(worldIn, mainmutable.setPos(pos).move(3, 22, 3));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(3, 22, 5));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(3, 22, 6));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(4, 22, 1));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(4, 22, 2));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(4, 22, 3));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(4, 22, 4));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(4, 22, 5));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(5, 22, 2));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(5, 22, 3));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(5, 22, 4));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(-1, 23, 2));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(-1, 23, 3));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(-1, 23, 4));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(0, 23, 1));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(0, 23, 2));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(0, 23, 3));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(0, 23, 4));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(0, 23, 5));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(1, 23, 0));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(1, 23, 1));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(1, 23, 2));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(1, 23, 4));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(1, 23, 5));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(1, 23, 6));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(2, 23, 0));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(2, 23, 1));
                this.shroomlight(worldIn, mainmutable.setPos(pos).move(2, 23, 2));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(2, 23, 5));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(2, 23, 6));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(3, 23, 0));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(3, 23, 1));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(3, 23, 2));
                this.shroomlight(worldIn, mainmutable.setPos(pos).move(3, 23, 3));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(3, 23, 4));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(3, 23, 5));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(3, 23, 6));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(4, 23, 1));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(4, 23, 2));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(4, 23, 3));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(4, 23, 4));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(4, 23, 5));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(5, 23, 2));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(5, 23, 3));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(5, 23, 4));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(0, 24, 1));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(0, 24, 2));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(0, 24, 3));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(0, 24, 4));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(0, 24, 5));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(1, 24, 1));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(1, 24, 2));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(1, 24, 3));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(1, 24, 4));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(1, 24, 5));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(2, 24, 1));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(2, 24, 2));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(2, 24, 3));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(2, 24, 4));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(2, 24, 5));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(3, 24, 1));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(3, 24, 2));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(3, 24, 3));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(3, 24, 4));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(3, 24, 5));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(4, 24, 1));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(4, 24, 2));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(4, 24, 3));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(4, 24, 4));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(4, 24, 5));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(1, 25, 2));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(1, 25, 3));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(1, 25, 4));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(2, 25, 2));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(2, 25, 3));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(2, 25, 4));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(3, 25, 2));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(3, 25, 3));
                placeMushroom(MUSHROOM, worldIn, mainmutable.setPos(pos).move(3, 25, 4));
            }
        }
        return true;
    }
    private void shroomlight(ISeedReader reader, BlockPos pos) {
        if (isAir(reader, pos)) {
            this.setFinalBlockState(reader, pos, BYGBlocks.PURPLE_SHROOMLIGHT.getDefaultState());
        }
    }
}