package corgiaoc.byg.common.world.feature.end.trees.bulbis;

import com.mojang.serialization.Codec;
import corgiaoc.byg.common.world.feature.config.BYGMushroomConfig;
import corgiaoc.byg.common.world.feature.overworld.mushrooms.util.BYGAbstractMushroomFeature;
import corgiaoc.byg.core.BYGBlocks;
import net.minecraft.block.BlockState;
import net.minecraft.util.math.BlockPos;
import net.minecraft.world.StructureWorldAccess;
import java.util.Random;

public class BulbisTree4 extends BYGAbstractMushroomFeature<BYGMushroomConfig> {

    public BulbisTree4(Codec<BYGMushroomConfig> configIn) {
        super(configIn);
    }

    protected boolean placeMushroom(StructureWorldAccess worldIn, Random rand, BlockPos pos, boolean isMushroom, BYGMushroomConfig config) {
        BlockState STEM = config.getStemProvider().getBlockState(rand, pos);
        BlockState MUSHROOM = config.getMushroomProvider().getBlockState(rand, pos);
        BlockState MUSHROOM2 = config.getMushroom2Provider().getBlockState(rand, pos);
        BlockState MUSHROOM3 = config.getMushroom3Provider().getBlockState(rand, pos);
        BlockState POLLEN = config.getPollenProvider().getBlockState(rand, pos);
        int randTreeHeight = 8 + rand.nextInt(5);
        BlockPos.Mutable mainmutable = new BlockPos.Mutable().set(pos);

        if (pos.getY() + randTreeHeight + 1 < worldIn.getHeight()) {
            if (!isDesiredGroundwEndTags(worldIn, pos.down(), BYGBlocks.IVIS_PHYLIUM)) {
                return false;
            } else if (!this.isAnotherMushroomLikeThisNearby(worldIn, pos, randTreeHeight, 0, STEM.getBlock(), MUSHROOM.getBlock(), isMushroom)) {
                return false;
            } else if (!this.doesMushroomHaveSpaceToGrow(worldIn, pos, randTreeHeight, 5, 5, 5, isMushroom)) {
                return false;
            } else {
                placeStem(STEM, worldIn, mainmutable.set(pos).move(0, 0, 0));
                placeStem(STEM, worldIn, mainmutable.set(pos).move(0, 1, 0));
                placeStem(STEM, worldIn, mainmutable.set(pos).move(0, 2, 0));
                placeStem(STEM, worldIn, mainmutable.set(pos).move(0, 3, 0));
                placeStem(STEM, worldIn, mainmutable.set(pos).move(0, 4, 0));
                placeStem(STEM, worldIn, mainmutable.set(pos).move(0, 5, 0));
                placeStem(STEM, worldIn, mainmutable.set(pos).move(0, 6, 0));
                placeStem(STEM, worldIn, mainmutable.set(pos).move(0, 7, 0));
                placeStemBranch(STEM, worldIn, mainmutable.set(pos).move(-1, 7, -1));
                placeStemBranch(STEM, worldIn, mainmutable.set(pos).move(-1, 7, 1));
                placeStemBranch(STEM, worldIn, mainmutable.set(pos).move(1, 7, -1));
                placeStemBranch(STEM, worldIn, mainmutable.set(pos).move(1, 7, 1));
                placeStemBranch(STEM, worldIn, mainmutable.set(pos).move(-2, 8, 2));
                placeStemBranch(STEM, worldIn, mainmutable.set(pos).move(-1, 8, -1));
                placeStemBranch(STEM, worldIn, mainmutable.set(pos).move(-1, 8, 1));
                placeStemBranch(STEM, worldIn, mainmutable.set(pos).move(1, 8, -1));
                placeStemBranch(STEM, worldIn, mainmutable.set(pos).move(1, 8, 1));
                placeStemBranch(STEM, worldIn, mainmutable.set(pos).move(2, 8, -2));
                placeStemBranch(STEM, worldIn, mainmutable.set(pos).move(-2, 9, -2));
                placeStemBranch(STEM, worldIn, mainmutable.set(pos).move(-2, 9, 2));
                placeStemBranch(STEM, worldIn, mainmutable.set(pos).move(-1, 9, -1));
                placeStemBranch(STEM, worldIn, mainmutable.set(pos).move(1, 9, 1));
                placeStemBranch(STEM, worldIn, mainmutable.set(pos).move(2, 9, -2));
                placeStemBranch(STEM, worldIn, mainmutable.set(pos).move(2, 9, 2));
                placeStemBranch(STEM, worldIn, mainmutable.set(pos).move(-3, 10, 2));
                placeStemBranch(STEM, worldIn, mainmutable.set(pos).move(-2, 10, -3));
                placeStemBranch(STEM, worldIn, mainmutable.set(pos).move(-2, 10, -2));
                placeStemBranch(STEM, worldIn, mainmutable.set(pos).move(-2, 10, 2));
                placeStemBranch(STEM, worldIn, mainmutable.set(pos).move(2, 10, -2));
                placeStemBranch(STEM, worldIn, mainmutable.set(pos).move(2, 10, 2));
                placeStemBranch(STEM, worldIn, mainmutable.set(pos).move(2, 10, 3));
                placeStemBranch(STEM, worldIn, mainmutable.set(pos).move(3, 10, -2));
                placeStemBranch(STEM, worldIn, mainmutable.set(pos).move(-3, 11, 2));
                placeStemBranch(STEM, worldIn, mainmutable.set(pos).move(-2, 11, -3));
                placeStemBranch(STEM, worldIn, mainmutable.set(pos).move(1, 11, 3));
                placeStemBranch(STEM, worldIn, mainmutable.set(pos).move(2, 11, 3));
                placeStemBranch(STEM, worldIn, mainmutable.set(pos).move(3, 11, -3));
                placeStemBranch(STEM, worldIn, mainmutable.set(pos).move(3, 11, -2));
                placeStemBranch(STEM, worldIn, mainmutable.set(pos).move(-4, 12, 2));
                placeStemBranch(STEM, worldIn, mainmutable.set(pos).move(-3, 12, 2));
                placeStemBranch(STEM, worldIn, mainmutable.set(pos).move(-2, 12, -3));
                placeStemBranch(STEM, worldIn, mainmutable.set(pos).move(1, 12, 3));
                placeStemBranch(STEM, worldIn, mainmutable.set(pos).move(3, 12, -3));
                placeStemBranch(STEM, worldIn, mainmutable.set(pos).move(-4, 13, 1));
                placeStemBranch(STEM, worldIn, mainmutable.set(pos).move(-4, 13, 2));
                placeStemBranch(STEM, worldIn, mainmutable.set(pos).move(-2, 13, -3));
                placeStemBranch(STEM, worldIn, mainmutable.set(pos).move(-1, 13, -2));
                placeStemBranch(STEM, worldIn, mainmutable.set(pos).move(1, 13, 3));
                placeStemBranch(STEM, worldIn, mainmutable.set(pos).move(3, 13, -3));
                placeStemBranch(STEM, worldIn, mainmutable.set(pos).move(4, 13, -3));
                placeStemBranch(STEM, worldIn, mainmutable.set(pos).move(-4, 14, 1));
                placeStemBranch(STEM, worldIn, mainmutable.set(pos).move(-1, 14, -2));
                placeStemBranch(STEM, worldIn, mainmutable.set(pos).move(1, 14, 3));
                placeStemBranch(STEM, worldIn, mainmutable.set(pos).move(1, 14, 4));
                placeStemBranch(STEM, worldIn, mainmutable.set(pos).move(4, 14, -3));
                placeStemBranch(STEM, worldIn, mainmutable.set(pos).move(4, 14, -2));
                placeStemBranch(STEM, worldIn, mainmutable.set(pos).move(-4, 15, 1));
                placeStemBranch(STEM, worldIn, mainmutable.set(pos).move(-1, 15, -2));
                placeStemBranch(STEM, worldIn, mainmutable.set(pos).move(1, 15, 4));
                placeStemBranch(STEM, worldIn, mainmutable.set(pos).move(4, 15, -2));
                placeStemBranch(STEM, worldIn, mainmutable.set(pos).move(-5, 16, 1));
                placeStemBranch(STEM, worldIn, mainmutable.set(pos).move(-4, 16, 1));
                placeStemBranch(STEM, worldIn, mainmutable.set(pos).move(-1, 16, -2));
                placeStemBranch(STEM, worldIn, mainmutable.set(pos).move(1, 16, 4));
                placeStemBranch(STEM, worldIn, mainmutable.set(pos).move(4, 16, -2));
                placeStemBranch(STEM, worldIn, mainmutable.set(pos).move(-5, 17, 1));
                placeStemBranch(STEM, worldIn, mainmutable.set(pos).move(1, 17, 4));
                placeStemBranch(STEM, worldIn, mainmutable.set(pos).move(4, 17, -2));
                placeStemBranch(STEM, worldIn, mainmutable.set(pos).move(-5, 18, 1));
                placeStemBranch(STEM, worldIn, mainmutable.set(pos).move(4, 18, -2));
                placeStemBranch(STEM, worldIn, mainmutable.set(pos).move(-5, 19, 0));
                placeStemBranch(STEM, worldIn, mainmutable.set(pos).move(-5, 19, 1));
                placeStemBranch(STEM, worldIn, mainmutable.set(pos).move(-5, 20, 0));
                placeStemBranch(STEM, worldIn, mainmutable.set(pos).move(-5, 21, 0));
                placeStemBranch(STEM, worldIn, mainmutable.set(pos).move(-5, 22, 0));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(-2, 15, -3));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(-2, 15, -2));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(-2, 15, -1));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(-1, 15, -3));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(-1, 15, -1));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(0, 15, -3));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(0, 15, -2));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(0, 15, -1));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(-3, 16, -3));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(-3, 16, -2));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(-3, 16, -1));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(-2, 16, -4));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(-2, 16, 0));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(-1, 16, -4));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(-1, 16, 0));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(0, 16, -4));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(0, 16, 0));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(0, 16, 3));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(0, 16, 4));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(0, 16, 5));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(1, 16, -3));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(1, 16, -2));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(1, 16, -1));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(1, 16, 3));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(1, 16, 5));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(2, 16, 3));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(2, 16, 4));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(2, 16, 5));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(-3, 17, -3));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(-3, 17, -2));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(-3, 17, -1));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(-2, 17, -4));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(-2, 17, 0));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(-1, 17, -4));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(-1, 17, 0));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(-1, 17, 3));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(-1, 17, 4));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(-1, 17, 5));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(0, 17, -4));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(0, 17, 0));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(0, 17, 2));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(0, 17, 6));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(1, 17, -3));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(1, 17, -2));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(1, 17, -1));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(1, 17, 2));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(1, 17, 6));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(2, 17, 2));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(2, 17, 6));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(3, 17, -3));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(3, 17, -2));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(3, 17, -1));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(3, 17, 3));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(3, 17, 4));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(3, 17, 5));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(4, 17, -3));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(4, 17, -1));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(5, 17, -3));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(5, 17, -2));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(5, 17, -1));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(-3, 18, -3));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(-3, 18, -2));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(-3, 18, -1));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(-2, 18, -4));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(-2, 18, 0));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(-1, 18, -4));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(-1, 18, 0));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(-1, 18, 3));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(-1, 18, 4));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(-1, 18, 5));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(0, 18, -4));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(0, 18, 0));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(0, 18, 2));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(0, 18, 6));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(1, 18, -3));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(1, 18, -2));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(1, 18, -1));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(1, 18, 2));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(1, 18, 6));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(2, 18, -3));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(2, 18, -2));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(2, 18, -1));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(2, 18, 2));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(2, 18, 6));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(3, 18, -4));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(3, 18, 0));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(3, 18, 3));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(3, 18, 4));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(3, 18, 5));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(4, 18, -4));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(4, 18, 0));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(5, 18, -4));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(5, 18, 0));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(6, 18, -3));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(6, 18, -2));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(6, 18, -1));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(-2, 19, -3));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(-2, 19, -2));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(-2, 19, -1));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(-1, 19, -3));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(-1, 19, -2));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(-1, 19, -1));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(-1, 19, 3));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(-1, 19, 4));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(-1, 19, 5));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(0, 19, -3));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(0, 19, -2));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(0, 19, -1));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(0, 19, 2));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(0, 19, 6));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(1, 19, 2));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(1, 19, 6));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(2, 19, -3));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(2, 19, -2));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(2, 19, -1));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(2, 19, 2));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(2, 19, 6));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(3, 19, -4));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(3, 19, 0));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(3, 19, 3));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(3, 19, 4));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(3, 19, 5));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(4, 19, -4));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(4, 19, 0));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(5, 19, -4));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(5, 19, 0));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(6, 19, -3));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(6, 19, -2));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(6, 19, -1));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(0, 20, 3));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(0, 20, 4));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(0, 20, 5));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(1, 20, 3));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(1, 20, 4));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(1, 20, 5));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(2, 20, -3));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(2, 20, -2));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(2, 20, -1));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(2, 20, 3));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(2, 20, 4));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(2, 20, 5));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(3, 20, -4));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(3, 20, 0));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(4, 20, -4));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(4, 20, 0));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(5, 20, -4));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(5, 20, 0));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(6, 20, -3));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(6, 20, -2));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(6, 20, -1));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(-6, 21, -1));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(-6, 21, 0));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(-6, 21, 1));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(-5, 21, -1));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(-5, 21, 1));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(-4, 21, -1));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(-4, 21, 0));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(-4, 21, 1));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(3, 21, -3));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(3, 21, -2));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(3, 21, -1));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(4, 21, -3));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(4, 21, -2));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(4, 21, -1));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(5, 21, -3));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(5, 21, -2));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(5, 21, -1));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(-7, 22, -1));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(-7, 22, 0));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(-7, 22, 1));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(-6, 22, -2));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(-6, 22, 2));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(-5, 22, -2));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(-5, 22, 2));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(-4, 22, -2));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(-4, 22, 2));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(-3, 22, -1));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(-3, 22, 0));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(-3, 22, 1));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(-7, 23, -1));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(-7, 23, 0));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(-7, 23, 1));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(-6, 23, -2));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(-6, 23, 2));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(-5, 23, -2));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(-5, 23, 2));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(-4, 23, -2));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(-4, 23, 2));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(-3, 23, -1));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(-3, 23, 0));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(-3, 23, 1));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(-7, 24, -1));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(-7, 24, 0));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(-7, 24, 1));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(-6, 24, -2));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(-6, 24, 2));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(-5, 24, -2));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(-5, 24, 2));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(-4, 24, -2));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(-4, 24, 2));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(-3, 24, -1));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(-3, 24, 0));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(-3, 24, 1));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(-6, 25, -1));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(-6, 25, 0));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(-6, 25, 1));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(-5, 25, -1));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(-5, 25, 0));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(-5, 25, 1));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(-4, 25, -1));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(-4, 25, 0));
                placeMushroom(MUSHROOM, worldIn, mainmutable.set(pos).move(-4, 25, 1));
            }
        }
        return true;
    }
}