package voronoiaoc.byg.common.world.feature.features.overworld.trees.cypress;

import com.mojang.datafixers.Dynamic;
import net.minecraft.util.Direction;
import net.minecraft.util.math.BlockPos;
import net.minecraft.util.math.MutableBoundingBox;
import net.minecraft.world.gen.IWorldGenerationBaseReader;
import net.minecraft.world.gen.IWorldGenerationReader;
import net.minecraft.world.gen.feature.NoFeatureConfig;
import voronoiaoc.byg.common.world.feature.features.overworld.trees.util.BYGAbstractTreeFeature;
import voronoiaoc.byg.core.byglists.BYGBlockList;

import java.util.Random;
import java.util.Set;
import java.util.function.Function;

public class CypressTree1 extends BYGAbstractTreeFeature<NoFeatureConfig> {


    public CypressTree1(Function<Dynamic<?>, ? extends NoFeatureConfig> configIn) {
        super(configIn);
    }

    /**
     *TODO: Redo
     */
    protected boolean place(Set<BlockPos> changedBlocks, IWorldGenerationReader worldIn, Random rand, BlockPos pos, MutableBoundingBox boundsIn) {
        int randTreeHeight = 19;
        BlockPos.Mutable mainmutable = new BlockPos.Mutable(pos);

        if (pos.getY() >= 1 && pos.getY() + randTreeHeight + 1 < worldIn.getMaxHeight()) {
            BlockPos blockpos = pos.down();
            if (!isSoil(worldIn, blockpos, getSapling())) {
                return false;
            } else if (!this.doesTreeFit(worldIn, pos, randTreeHeight)) {
                return false;
            } else {
                for (int buildTrunk = 0; buildTrunk <= randTreeHeight; buildTrunk++) {
                    this.treeLog(changedBlocks, worldIn, mainmutable.move(Direction.UP), boundsIn);
                }
                mainmutable.setPos(pos);

                this.treeLog(changedBlocks, worldIn, mainmutable.add(0, 0, 0), boundsIn);
                this.treeLog(changedBlocks, worldIn, mainmutable.add(0, 1, 0), boundsIn);
                this.treeLog(changedBlocks, worldIn, mainmutable.add(0, 2, 0), boundsIn);
                this.treeLog(changedBlocks, worldIn, mainmutable.add(0, 3, 0), boundsIn);
                this.treeLog(changedBlocks, worldIn, mainmutable.add(0, 4, 0), boundsIn);
                this.treeLog(changedBlocks, worldIn, mainmutable.add(0, 5, 0), boundsIn);
                this.treeLog(changedBlocks, worldIn, mainmutable.add(0, 6, 0), boundsIn);
                this.treeLog(changedBlocks, worldIn, mainmutable.add(0, 7, 0), boundsIn);
                this.treeLog(changedBlocks, worldIn, mainmutable.add(0, 8, 0), boundsIn);
                this.treeLog(changedBlocks, worldIn, mainmutable.add(0, 9, 0), boundsIn);
                this.treeLog(changedBlocks, worldIn, mainmutable.add(0, 10, 0), boundsIn);
                this.treeLog(changedBlocks, worldIn, mainmutable.add(0, 11, 0), boundsIn);
                this.treeLog(changedBlocks, worldIn, mainmutable.add(0, 12, 0), boundsIn);
                this.treeLog(changedBlocks, worldIn, mainmutable.add(0, 13, 0), boundsIn);
                this.treeLog(changedBlocks, worldIn, mainmutable.add(0, 14, 0), boundsIn);
                this.treeLog(changedBlocks, worldIn, mainmutable.add(0, 15, 0), boundsIn);
                this.treeLog(changedBlocks, worldIn, mainmutable.add(0, 16, 0), boundsIn);
                this.treeLog(changedBlocks, worldIn, mainmutable.add(0, 17, 0), boundsIn);
                this.treeLog(changedBlocks, worldIn, mainmutable.add(0, 18, 0), boundsIn);
                this.treeLog(changedBlocks, worldIn, mainmutable.add(0, 19, 0), boundsIn);

                this.treeLog(changedBlocks, worldIn, mainmutable.add(0, 0, -1), boundsIn);
                this.treeLog(changedBlocks, worldIn, mainmutable.add(-1, 0, 0), boundsIn);
                this.treeLog(changedBlocks, worldIn, mainmutable.add(1, 0, 0), boundsIn);
                this.treeLog(changedBlocks, worldIn, mainmutable.add(0, 0, 1), boundsIn);
                this.treeLog(changedBlocks, worldIn, mainmutable.add(0, 1, -1), boundsIn);
                this.treeLog(changedBlocks, worldIn, mainmutable.add(-1, 1, 0), boundsIn);
                this.treeLog(changedBlocks, worldIn, mainmutable.add(1, 1, 0), boundsIn);
                this.treeLog(changedBlocks, worldIn, mainmutable.add(0, 1, 1), boundsIn);
                this.treeLog(changedBlocks, worldIn, mainmutable.add(0, 2, -1), boundsIn);
                this.treeLog(changedBlocks, worldIn, mainmutable.add(-1, 2, 0), boundsIn);
                this.treeLog(changedBlocks, worldIn, mainmutable.add(1, 2, 0), boundsIn);
                this.treeLog(changedBlocks, worldIn, mainmutable.add(0, 2, 1), boundsIn);
                this.treeLog(changedBlocks, worldIn, mainmutable.add(0, 3, -1), boundsIn);
                this.treeLog(changedBlocks, worldIn, mainmutable.add(-1, 3, 0), boundsIn);
                this.treeLog(changedBlocks, worldIn, mainmutable.add(1, 3, 0), boundsIn);
                this.treeLog(changedBlocks, worldIn, mainmutable.add(0, 3, 1), boundsIn);
                this.treeLog(changedBlocks, worldIn, mainmutable.add(0, 4, -1), boundsIn);
                this.treeLog(changedBlocks, worldIn, mainmutable.add(-1, 4, 0), boundsIn);
                this.treeLog(changedBlocks, worldIn, mainmutable.add(1, 4, 0), boundsIn);
                this.treeLog(changedBlocks, worldIn, mainmutable.add(0, 4, 1), boundsIn);
                this.treeLog(changedBlocks, worldIn, mainmutable.add(0, 5, -1), boundsIn);
                this.treeLog(changedBlocks, worldIn, mainmutable.add(-1, 5, 0), boundsIn);
                this.treeLog(changedBlocks, worldIn, mainmutable.add(1, 5, 0), boundsIn);
                this.treeLog(changedBlocks, worldIn, mainmutable.add(0, 5, 1), boundsIn);
                this.treeLog(changedBlocks, worldIn, mainmutable.add(0, 6, -1), boundsIn);
                this.treeLog(changedBlocks, worldIn, mainmutable.add(-1, 6, 0), boundsIn);
                this.treeLog(changedBlocks, worldIn, mainmutable.add(1, 6, 0), boundsIn);
                this.treeLog(changedBlocks, worldIn, mainmutable.add(0, 6, 1), boundsIn);
                this.treeLog(changedBlocks, worldIn, mainmutable.add(0, 7, -1), boundsIn);
                this.treeLog(changedBlocks, worldIn, mainmutable.add(-1, 7, 0), boundsIn);
                this.treeLog(changedBlocks, worldIn, mainmutable.add(1, 7, 0), boundsIn);
                this.treeLog(changedBlocks, worldIn, mainmutable.add(0, 7, 1), boundsIn);
                this.treeLog(changedBlocks, worldIn, mainmutable.add(0, 8, -1), boundsIn);
                this.treeLog(changedBlocks, worldIn, mainmutable.add(-1, 8, 0), boundsIn);
                this.treeLog(changedBlocks, worldIn, mainmutable.add(1, 8, 0), boundsIn);
                this.treeLog(changedBlocks, worldIn, mainmutable.add(0, 8, 1), boundsIn);
                this.treeLog(changedBlocks, worldIn, mainmutable.add(0, 9, -1), boundsIn);
                this.treeLog(changedBlocks, worldIn, mainmutable.add(-1, 9, 0), boundsIn);
                this.treeLog(changedBlocks, worldIn, mainmutable.add(1, 9, 0), boundsIn);
                this.treeLog(changedBlocks, worldIn, mainmutable.add(0, 9, 1), boundsIn);
                this.treeLog(changedBlocks, worldIn, mainmutable.add(0, 10, -1), boundsIn);
                this.treeLog(changedBlocks, worldIn, mainmutable.add(-1, 10, 0), boundsIn);
                this.treeLog(changedBlocks, worldIn, mainmutable.add(1, 10, 0), boundsIn);
                this.treeLog(changedBlocks, worldIn, mainmutable.add(0, 10, 1), boundsIn);
                this.treeLog(changedBlocks, worldIn, mainmutable.add(0, 11, -1), boundsIn);
                this.treeLog(changedBlocks, worldIn, mainmutable.add(-1, 11, 0), boundsIn);
                this.treeLog(changedBlocks, worldIn, mainmutable.add(1, 11, 0), boundsIn);
                this.treeLog(changedBlocks, worldIn, mainmutable.add(0, 11, 1), boundsIn);
                this.treeLog(changedBlocks, worldIn, mainmutable.add(0, 12, -1), boundsIn);
                this.treeLog(changedBlocks, worldIn, mainmutable.add(-1, 12, 0), boundsIn);
                this.treeLog(changedBlocks, worldIn, mainmutable.add(1, 12, 0), boundsIn);
                this.treeLog(changedBlocks, worldIn, mainmutable.add(0, 12, 1), boundsIn);
                this.treeLog(changedBlocks, worldIn, mainmutable.add(0, 13, -1), boundsIn);
                this.treeLog(changedBlocks, worldIn, mainmutable.add(-1, 13, 0), boundsIn);
                this.treeLog(changedBlocks, worldIn, mainmutable.add(1, 13, 0), boundsIn);
                this.treeLog(changedBlocks, worldIn, mainmutable.add(0, 13, 1), boundsIn);
                this.treeLog(changedBlocks, worldIn, mainmutable.add(0, 14, -1), boundsIn);
                this.treeLog(changedBlocks, worldIn, mainmutable.add(-1, 14, 0), boundsIn);
                this.treeLog(changedBlocks, worldIn, mainmutable.add(1, 14, 0), boundsIn);
                this.treeLog(changedBlocks, worldIn, mainmutable.add(0, 14, 1), boundsIn);
                this.treeLog(changedBlocks, worldIn, mainmutable.add(0, 15, -1), boundsIn);
                this.treeLog(changedBlocks, worldIn, mainmutable.add(-1, 15, 0), boundsIn);
                this.treeLog(changedBlocks, worldIn, mainmutable.add(1, 15, 0), boundsIn);
                this.treeLog(changedBlocks, worldIn, mainmutable.add(0, 15, 1), boundsIn);
//                this.treeLog(changedBlocks, worldIn, mainmutable.add(0, 16, -1), boundsIn);
//                this.treeLog(changedBlocks, worldIn, mainmutable.add(-1, 16, 0), boundsIn);
//                this.treeLog(changedBlocks, worldIn, mainmutable.add(1, 16, 0), boundsIn);
//                this.treeLog(changedBlocks, worldIn, mainmutable.add(0, 16, 1), boundsIn);
//                this.treeLog(changedBlocks, worldIn, mainmutable.add(0, 17, -1), boundsIn);
//                this.treeLog(changedBlocks, worldIn, mainmutable.add(-1, 17, 0), boundsIn);
//                this.treeLog(changedBlocks, worldIn, mainmutable.add(1, 17, 0), boundsIn);
//                this.treeLog(changedBlocks, worldIn, mainmutable.add(0, 17, 1), boundsIn);
//                this.treeLog(changedBlocks, worldIn, mainmutable.add(0, 18, -1), boundsIn);
//                this.treeLog(changedBlocks, worldIn, mainmutable.add(-1, 18, 0), boundsIn);
//                this.treeLog(changedBlocks, worldIn, mainmutable.add(1, 18, 0), boundsIn);
//                this.treeLog(changedBlocks, worldIn, mainmutable.add(0, 18, 1), boundsIn);
                this.treeLog(changedBlocks, worldIn, mainmutable.add(0, 19, -1), boundsIn);
                this.treeLog(changedBlocks, worldIn, mainmutable.add(-1, 19, 0), boundsIn);
                this.treeLog(changedBlocks, worldIn, mainmutable.add(1, 19, 0), boundsIn);
                this.treeLog(changedBlocks, worldIn, mainmutable.add(0, 19, 1), boundsIn);

                this.treeBranch(changedBlocks, worldIn, mainmutable.add(0, 0, -5), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(-4, 0, -4), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(-1, 0, -4), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(0, 0, -4), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(1, 0, -4), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(4, 0, -4), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(0, 0, -3), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(-4, 0, -1), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(4, 0, -1), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(-5, 0, 0), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(-4, 0, 0), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(-3, 0, 0), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(3, 0, 0), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(4, 0, 0), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(5, 0, 0), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(-4, 0, 1), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(4, 0, 1), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(0, 0, 3), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(-4, 0, 4), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(-1, 0, 4), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(0, 0, 4), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(1, 0, 4), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(4, 0, 4), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(0, 0, 5), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(0, 1, -5), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(-4, 1, -4), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(-1, 1, -4), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(0, 1, -4), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(1, 1, -4), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(4, 1, -4), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(-3, 1, -3), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(0, 1, -3), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(3, 1, -3), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(-4, 1, -1), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(4, 1, -1), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(-5, 1, 0), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(-4, 1, 0), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(-3, 1, 0), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(3, 1, 0), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(4, 1, 0), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(5, 1, 0), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(-4, 1, 1), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(4, 1, 1), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(-3, 1, 3), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(0, 1, 3), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(3, 1, 3), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(-4, 1, 4), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(-1, 1, 4), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(0, 1, 4), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(1, 1, 4), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(4, 1, 4), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(0, 1, 5), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(0, 2, -4), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(-3, 2, -3), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(3, 2, -3), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(-4, 2, 0), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(4, 2, 0), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(-3, 2, 3), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(3, 2, 3), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(0, 2, 4), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(0, 3, -4), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(-3, 3, -3), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(-2, 3, -3), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(0, 3, -3), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(2, 3, -3), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(3, 3, -3), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(-3, 3, -2), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(3, 3, -2), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(-4, 3, 0), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(-3, 3, 0), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(3, 3, 0), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(4, 3, 0), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(-3, 3, 2), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(3, 3, 2), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(-3, 3, 3), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(-2, 3, 3), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(0, 3, 3), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(2, 3, 3), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(3, 3, 3), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(0, 3, 4), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(0, 4, -3), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(-2, 4, -2), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(2, 4, -2), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(-3, 4, 0), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(3, 4, 0), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(-1, 4, 1), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(1, 4, 1), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(-2, 4, 2), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(2, 4, 2), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(0, 4, 3), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(0, 5, -3), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(-1, 5, -2), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(0, 5, -2), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(1, 5, -2), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(-2, 5, -1), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(-1, 5, -1), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(1, 5, -1), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(2, 5, -1), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(-3, 5, 0), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(-2, 5, 0), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(2, 5, 0), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(3, 5, 0), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(-2, 5, 1), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(-1, 5, 1), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(1, 5, 1), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(2, 5, 1), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(-1, 5, 2), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(0, 5, 2), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(1, 5, 2), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(0, 5, 3), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(0, 6, -3), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(0, 6, -2), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(-1, 6, -1), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(1, 6, -1), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(-3, 6, 0), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(-2, 6, 0), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(2, 6, 0), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(3, 6, 0), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(-1, 6, 1), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(1, 6, 1), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(0, 6, 2), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(0, 6, 3), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(0, 7, -3), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(0, 7, -2), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(-1, 7, -1), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(1, 7, -1), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(-2, 7, 0), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(2, 7, 0), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(-1, 7, 1), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(1, 7, 1), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(0, 7, 2), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(0, 7, 3), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(0, 8, -2), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(-1, 8, -1), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(1, 8, -1), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(-2, 8, 0), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(2, 8, 0), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(-1, 8, 1), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(1, 8, 1), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(0, 8, 2), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(0, 9, -2), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(-2, 9, 0), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(2, 9, 0), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(0, 9, 2), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(0, 16, -2), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(-2, 16, 0), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(2, 16, 0), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(0, 16, 2), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(0, 17, -3), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(0, 17, -2), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(-3, 17, 0), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(-2, 17, 0), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(2, 17, 0), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(3, 17, 0), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(0, 17, 2), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(0, 17, 3), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(0, 18, -2), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(-2, 18, 0), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(2, 18, 0), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(0, 18, 2), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(1, 19, -7), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(1, 19, -6), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(-3, 19, -5), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(0, 19, -5), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(2, 19, -5), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(-2, 19, -4), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(-1, 19, -4), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(0, 19, -4), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(3, 19, -4), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(4, 19, -4), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(-5, 19, -3), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(0, 19, -3), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(2, 19, -3), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(3, 19, -3), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(-4, 19, -2), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(0, 19, -2), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(8, 19, -2), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(-4, 19, -1), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(6, 19, -1), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(7, 19, -1), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(-5, 19, 0), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(-4, 19, 0), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(-3, 19, 0), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(-2, 19, 0), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(2, 19, 0), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(3, 19, 0), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(4, 19, 0), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(5, 19, 0), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(-2, 19, 1), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(-3, 19, 2), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(0, 19, 2), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(-4, 19, 3), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(0, 19, 3), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(3, 19, 3), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(4, 19, 3), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(-4, 19, 4), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(0, 19, 4), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(2, 19, 4), boundsIn);
                this.treeBranch(changedBlocks, worldIn, mainmutable.add(1, 19, 5), boundsIn);

                this.leafs(changedBlocks, worldIn, mainmutable.add(-5, 2, -3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-5, 2, -2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-4, 2, -2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-6, 2, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-5, 2, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-4, 2, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-8, 2, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-7, 2, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-6, 2, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-5, 2, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-7, 2, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-6, 2, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-5, 2, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-4, 2, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-5, 2, 2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(2, 2, 2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(3, 2, 2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(4, 2, 2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-5, 2, 3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 2, 3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(2, 2, 3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(4, 2, 3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(5, 2, 3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(2, 2, 4), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(3, 2, 4), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(4, 2, 4), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(5, 2, 4), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(6, 2, 4), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(3, 2, 5), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(4, 2, 5), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(5, 2, 5), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(3, 2, 6), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 3, -8), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 3, -7), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 3, -7), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 3, -7), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 3, -6), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 3, -6), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 3, -6), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(2, 3, -6), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 3, -5), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 3, -5), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 3, -5), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(2, 3, -5), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(3, 3, -5), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-2, 3, -4), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 3, -4), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 3, -4), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(2, 3, -4), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(3, 3, -4), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 3, -3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 3, -3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-5, 3, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-6, 3, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-5, 3, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-6, 3, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-5, 3, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-5, 3, 2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(4, 3, 3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(3, 3, 4), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(4, 3, 4), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(5, 3, 4), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(4, 3, 5), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 4, -6), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 4, -5), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 4, -5), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 4, -4), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 4, -4), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 4, -4), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(2, 4, -4), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 4, -3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-5, 4, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 5, -4), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 16, -4), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(3, 16, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(2, 16, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 17, -6), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 17, -5), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 17, -5), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 17, -4), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 17, -4), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 17, -4), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 17, -3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 17, -3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(2, 17, -3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(3, 17, -3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(4, 17, -3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-4, 17, -2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-3, 17, -2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-2, 17, -2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 17, -2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 17, -2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(2, 17, -2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-2, 17, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 17, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 17, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(2, 17, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(3, 17, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-5, 17, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-4, 17, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(4, 17, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(5, 17, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-4, 17, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-3, 17, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-2, 17, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 17, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(2, 17, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(3, 17, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(4, 17, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-5, 17, 2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-4, 17, 2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-3, 17, 2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 17, 2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 17, 2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(2, 17, 2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(3, 17, 2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(4, 17, 2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-4, 17, 3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-3, 17, 3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 17, 3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 17, 3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(2, 17, 3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(3, 17, 3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-4, 17, 4), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 17, 4), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(2, 17, 4), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(2, 17, 5), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 18, -8), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 18, -8), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(2, 18, -8), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-3, 18, -7), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-2, 18, -7), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 18, -7), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 18, -7), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 18, -7), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(2, 18, -7), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(3, 18, -7), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-5, 18, -6), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-4, 18, -6), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-3, 18, -6), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-2, 18, -6), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 18, -6), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 18, -6), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 18, -6), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(2, 18, -6), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(3, 18, -6), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(4, 18, -6), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(5, 18, -6), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-6, 18, -5), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-5, 18, -5), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-4, 18, -5), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-3, 18, -5), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-2, 18, -5), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 18, -5), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 18, -5), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 18, -5), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(2, 18, -5), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(3, 18, -5), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(4, 18, -5), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(5, 18, -5), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(6, 18, -5), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-7, 18, -4), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-6, 18, -4), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-5, 18, -4), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-4, 18, -4), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-3, 18, -4), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-2, 18, -4), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 18, -4), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 18, -4), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 18, -4), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(2, 18, -4), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(3, 18, -4), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(4, 18, -4), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(5, 18, -4), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(6, 18, -4), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(7, 18, -4), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(8, 18, -4), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-7, 18, -3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-6, 18, -3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-5, 18, -3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-4, 18, -3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-3, 18, -3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-2, 18, -3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 18, -3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 18, -3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 18, -3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(2, 18, -3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(3, 18, -3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(4, 18, -3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(5, 18, -3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(6, 18, -3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(7, 18, -3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(8, 18, -3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(9, 18, -3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-7, 18, -2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-6, 18, -2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-5, 18, -2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-4, 18, -2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-3, 18, -2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-2, 18, -2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 18, -2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 18, -2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(2, 18, -2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(3, 18, -2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(4, 18, -2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(5, 18, -2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(6, 18, -2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(7, 18, -2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(8, 18, -2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(9, 18, -2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(10, 18, -2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-8, 18, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-7, 18, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-6, 18, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-5, 18, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-4, 18, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-3, 18, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-2, 18, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 18, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 18, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 18, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(2, 18, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(3, 18, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(4, 18, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(5, 18, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(6, 18, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(7, 18, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(8, 18, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(9, 18, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(10, 18, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(11, 18, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(12, 18, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-9, 18, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-8, 18, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-7, 18, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-6, 18, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-5, 18, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-4, 18, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-3, 18, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 18, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 18, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(3, 18, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(4, 18, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(5, 18, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(6, 18, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(7, 18, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(8, 18, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(9, 18, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(10, 18, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(11, 18, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-8, 18, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-7, 18, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-6, 18, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-5, 18, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-4, 18, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-3, 18, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-2, 18, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 18, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 18, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 18, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(2, 18, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(3, 18, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(4, 18, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(5, 18, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(6, 18, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(7, 18, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(8, 18, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(9, 18, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-7, 18, 2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-6, 18, 2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-5, 18, 2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-4, 18, 2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-3, 18, 2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-2, 18, 2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 18, 2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 18, 2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(2, 18, 2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(3, 18, 2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(4, 18, 2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(5, 18, 2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(6, 18, 2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(7, 18, 2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(8, 18, 2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(9, 18, 2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-7, 18, 3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-6, 18, 3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-5, 18, 3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-4, 18, 3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-3, 18, 3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-2, 18, 3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 18, 3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 18, 3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 18, 3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(2, 18, 3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(3, 18, 3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(4, 18, 3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(5, 18, 3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(6, 18, 3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(7, 18, 3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(8, 18, 3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-6, 18, 4), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-5, 18, 4), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-4, 18, 4), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-3, 18, 4), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-2, 18, 4), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 18, 4), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 18, 4), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 18, 4), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(2, 18, 4), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(3, 18, 4), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(4, 18, 4), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(5, 18, 4), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(6, 18, 4), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-6, 18, 5), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-5, 18, 5), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-4, 18, 5), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-3, 18, 5), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-2, 18, 5), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 18, 5), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 18, 5), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 18, 5), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(2, 18, 5), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(3, 18, 5), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(4, 18, 5), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-5, 18, 6), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-4, 18, 6), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-3, 18, 6), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 18, 6), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 18, 6), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(2, 18, 6), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(3, 18, 6), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-4, 18, 7), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-3, 18, 7), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-4, 18, 8), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 19, -8), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 19, -7), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(2, 19, -7), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-4, 19, -6), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-3, 19, -6), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-2, 19, -6), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 19, -6), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 19, -6), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(2, 19, -6), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(3, 19, -6), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-5, 19, -5), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-4, 19, -5), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-2, 19, -5), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 19, -5), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 19, -5), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(3, 19, -5), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(4, 19, -5), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(5, 19, -5), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-5, 19, -4), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-4, 19, -4), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-3, 19, -4), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 19, -4), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(2, 19, -4), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(5, 19, -4), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(6, 19, -4), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-6, 19, -3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-4, 19, -3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-3, 19, -3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-2, 19, -3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 19, -3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 19, -3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(4, 19, -3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(5, 19, -3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(6, 19, -3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(7, 19, -3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(8, 19, -3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-6, 19, -2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-5, 19, -2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-3, 19, -2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-2, 19, -2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 19, -2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 19, -2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(2, 19, -2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(3, 19, -2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(4, 19, -2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(5, 19, -2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(6, 19, -2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(7, 19, -2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(9, 19, -2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-6, 19, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-5, 19, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-3, 19, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-2, 19, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 19, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 19, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(2, 19, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(3, 19, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(4, 19, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(5, 19, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(8, 19, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(9, 19, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(10, 19, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-8, 19, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-7, 19, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-6, 19, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(6, 19, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(7, 19, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(8, 19, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(9, 19, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-7, 19, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-6, 19, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-5, 19, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-4, 19, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-3, 19, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 19, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 19, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(2, 19, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(3, 19, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(4, 19, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(5, 19, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(6, 19, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(7, 19, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(8, 19, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-7, 19, 2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-6, 19, 2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-5, 19, 2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-4, 19, 2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-2, 19, 2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 19, 2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 19, 2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(2, 19, 2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(3, 19, 2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(4, 19, 2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(5, 19, 2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(6, 19, 2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(7, 19, 2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-6, 19, 3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-5, 19, 3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-3, 19, 3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-2, 19, 3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 19, 3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 19, 3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(2, 19, 3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(5, 19, 3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(6, 19, 3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-5, 19, 4), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-3, 19, 4), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-2, 19, 4), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 19, 4), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 19, 4), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(3, 19, 4), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(4, 19, 4), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(5, 19, 4), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-5, 19, 5), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-4, 19, 5), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-3, 19, 5), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 19, 5), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 19, 5), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(2, 19, 5), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(3, 19, 5), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-4, 19, 6), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 19, 6), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 20, -7), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 20, -6), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-4, 20, -5), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-3, 20, -5), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-2, 20, -5), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 20, -5), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 20, -5), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(2, 20, -5), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(3, 20, -5), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-4, 20, -4), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-3, 20, -4), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-2, 20, -4), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 20, -4), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 20, -4), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 20, -4), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(2, 20, -4), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(3, 20, -4), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(4, 20, -4), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(5, 20, -4), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-5, 20, -3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-4, 20, -3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-3, 20, -3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-2, 20, -3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 20, -3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 20, -3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 20, -3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(2, 20, -3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(3, 20, -3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(4, 20, -3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(5, 20, -3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(6, 20, -3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-5, 20, -2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-4, 20, -2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-3, 20, -2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-2, 20, -2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 20, -2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 20, -2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 20, -2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(2, 20, -2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(3, 20, -2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(4, 20, -2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(5, 20, -2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(6, 20, -2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(7, 20, -2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(8, 20, -2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-5, 20, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-4, 20, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-3, 20, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-2, 20, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 20, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 20, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 20, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(2, 20, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(3, 20, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(4, 20, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(5, 20, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(6, 20, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(7, 20, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(8, 20, -1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-6, 20, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-5, 20, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-4, 20, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-3, 20, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-2, 20, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 20, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 20, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 20, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(2, 20, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(3, 20, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(4, 20, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(5, 20, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(6, 20, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(7, 20, 0), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-6, 20, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-5, 20, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-4, 20, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-3, 20, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-2, 20, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 20, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 20, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 20, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(2, 20, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(3, 20, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(4, 20, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(5, 20, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(6, 20, 1), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-6, 20, 2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-5, 20, 2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-4, 20, 2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-3, 20, 2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-2, 20, 2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 20, 2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 20, 2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 20, 2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(2, 20, 2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(3, 20, 2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(4, 20, 2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(5, 20, 2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(6, 20, 2), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-5, 20, 3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-4, 20, 3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-3, 20, 3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-2, 20, 3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 20, 3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 20, 3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 20, 3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(2, 20, 3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(3, 20, 3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(4, 20, 3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(5, 20, 3), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-4, 20, 4), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-3, 20, 4), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(-1, 20, 4), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(0, 20, 4), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 20, 4), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(2, 20, 4), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(3, 20, 4), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(4, 20, 4), boundsIn);
                this.leafs(changedBlocks, worldIn, mainmutable.add(1, 20, 5), boundsIn);
            }
        }
        return true;
    }

    //Log Placement
    private void treeLog(Set<BlockPos> setlogblock, IWorldGenerationReader reader, BlockPos pos, MutableBoundingBox boundingBox) {
        if (canTreePlaceHere(reader, pos)) {
            this.setFinalBlockState(setlogblock, reader, pos, BYGBlockList.PINE_LOG.getDefaultState(), boundingBox);
        }
    }

    //Log Placement
    private void treeBranch(Set<BlockPos> setlogblock, IWorldGenerationReader reader, BlockPos pos, MutableBoundingBox boundingBox) {
        if (canTreePlaceHere(reader, pos)) {
            this.setFinalBlockState(setlogblock, reader, pos, BYGBlockList.PINE_LOG.getDefaultState(), boundingBox);
        }
    }

    //Leaves Placement
    private void leafs(Set<BlockPos> blockPos, IWorldGenerationReader reader, BlockPos pos, MutableBoundingBox boundingBox) {
        BlockPos.Mutable blockpos = new BlockPos.Mutable(pos);
        if (isAir(reader, blockpos)) {
            this.setFinalBlockState(blockPos, reader, blockpos,  BYGBlockList.PINE_LEAVES.getDefaultState(), boundingBox);
        }
    }



    private boolean doesTreeFit(IWorldGenerationBaseReader reader, BlockPos blockPos, int height) {
        int x = blockPos.getX();
        int y = blockPos.getY();
        int z = blockPos.getZ();
        BlockPos.Mutable pos = new BlockPos.Mutable();

        for (int yOffset = 0; yOffset <= height + 1; ++yOffset) {
            //Distance/Density of trees. Positive Values ONLY
            int distance = 2;

            for (int xOffset = -distance; xOffset <= distance; ++xOffset) {
                for (int zOffset = -distance; zOffset <= distance; ++zOffset) {
                    if (!canTreePlaceHereWater(reader, pos.setPos(x + xOffset, y + yOffset, z + zOffset))) {
                        return false;
                    }
                }
            }
        }
        return true;
    }
}